/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiFunctions generated by hbm2java
 */
public class SbiFunctions  implements java.io.Serializable {

    // Fields    

     private Integer functId;
     private SbiDomains functType;
     private SbiFunctions parentFunct;
     private String functTypeCd;
     private String code;
     private String name;
     private String descr;
     private String path;
     private Set sbiObjFuncs;
     private Set sbiFuncRoles;


    // Constructors

    /** default constructor */
    public SbiFunctions() {
    }
    
    /** constructor with id */
    public SbiFunctions(Integer functId) {
        this.functId = functId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getFunctId() {
        return this.functId;
    }
    
    public void setFunctId(Integer functId) {
        this.functId = functId;
    }


    /**
     * 
     */
    public String getFunctTypeCd() {
        return this.functTypeCd;
    }
    
    public void setFunctTypeCd(String functTypeCd) {
        this.functTypeCd = functTypeCd;
    }

    /**
     * 
     */
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * 
     */
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * 
     */
    public Set getSbiObjFuncs() {
        return this.sbiObjFuncs;
    }
    
    public void setSbiObjFuncs(Set sbiObjFuncs) {
        this.sbiObjFuncs = sbiObjFuncs;
    }

    /**
     * 
     */
    public Set getSbiFuncRoles() {
        return this.sbiFuncRoles;
    }
    
    public void setSbiFuncRoles(Set sbiFuncRoles) {
        this.sbiFuncRoles = sbiFuncRoles;
    }



	public SbiDomains getFunctType() {
		return functType;
	}
	public void setFunctType(SbiDomains functType) {
		this.functType = functType;
	}
	public SbiFunctions getParentFunct() {
		return parentFunct;
	}
	public void setParentFunct(SbiFunctions parentFunct) {
		this.parentFunct = parentFunct;
	}
}