--Chiara 27/05/2010
ALTER TABLE SBI_RESOURCES ADD RESOURCE_CODE VARCHAR2(45);
UPDATE SBI_RESOURCES SET RESOURCE_CODE = RESOURCE_NAME;
CREATE UNIQUE INDEX UNIQUE_RES_CODE ON SBI_RESOURCES(RESOURCE_CODE);
ALTER TABLE SBI_RESOURCES MODIFY RESOURCE_CODE VARCHAR2(45) NOT NULL;

--Giulio 31/05/2010
CREATE SEQUENCE SBI_KPI_MODEL_ATTR_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER
/
