package it.eng.spagobi.tools.distributionlist.metadata;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3



/**
 * SbiDistributionListUser generated by hbm2java
 */

public class SbiDistributionListUser  implements java.io.Serializable {


    // Fields    

     private Integer dluId;
     private SbiDistributionList sbiDistributionList;
     private String userId;
     private String EMail;


     public SbiDistributionListUser() {
     }

     
     /** full constructor */
     public SbiDistributionListUser(Integer dluId, SbiDistributionList sbiDistributionList, String userId, String EMail) {
         this.dluId = dluId;
         this.sbiDistributionList = sbiDistributionList;
         this.userId = userId;
         this.EMail = EMail;
     }
     

    
     // Property accessors

     public Integer getDluId() {
         return this.dluId;
     }
     
     public void setDluId(Integer dluId) {
         this.dluId = dluId;
     }

     public SbiDistributionList getSbiDistributionList() {
         return this.sbiDistributionList;
     }
     
     public void setSbiDistributionList(SbiDistributionList sbiDistributionList) {
         this.sbiDistributionList = sbiDistributionList;
     }

     public String getUserId() {
         return this.userId;
     }
     
     public void setUserId(String userId) {
         this.userId = userId;
     }

     public String getEMail() {
         return this.EMail;
     }
     
     public void setEMail(String EMail) {
         this.EMail = EMail;
     }
    
}
