package it.eng.spagobi.tools.distributionlist.metadata;

import it.eng.spagobi.analiticalmodel.document.metadata.SbiObjects;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3



/**
 * SbiDistributionListsObjects generated by hbm2java
 */

public class SbiDistributionListsObjects  implements java.io.Serializable {


    // Fields    

     private Integer relId;
     private SbiObjects sbiObjects;
     private SbiDistributionList sbiDistributionList;
     private String xml;


    // Constructors

    /** default constructor */
    public SbiDistributionListsObjects() {
    }

    
    /** full constructor */
    public SbiDistributionListsObjects(Integer relId, SbiObjects sbiObjects, SbiDistributionList sbiDistributionList, String xml) {
        this.relId = relId;
        this.sbiObjects = sbiObjects;
        this.sbiDistributionList = sbiDistributionList;
        this.xml = xml;
    }
    

   
    // Property accessors

    public Integer getRelId() {
        return this.relId;
    }
    
    public void setRelId(Integer relId) {
        this.relId = relId;
    }

    public SbiObjects getSbiObjects() {
        return this.sbiObjects;
    }
    
    public void setSbiObjects(SbiObjects sbiObjects) {
        this.sbiObjects = sbiObjects;
    }

    public SbiDistributionList getSbiDistributionList() {
        return this.sbiDistributionList;
    }
    
    public void setSbiDistributionList(SbiDistributionList sbiDistributionList) {
        this.sbiDistributionList = sbiDistributionList;
    }

    public String getXml() {
        return this.xml;
    }
    
    public void setXml(String xml) {
        this.xml = xml;
    }
   








}
