/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.tools.distributionlist.metadata;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3



/**
 * SbiDistributionListUser generated by hbm2java
 */

public class SbiDistributionListUser  implements java.io.Serializable {


    // Fields    

     private Integer dluId;
     private SbiDistributionList sbiDistributionList;
     private String userId;
     private String EMail;


     public SbiDistributionListUser() {
     }

     
     /** full constructor */
     public SbiDistributionListUser(Integer dluId, SbiDistributionList sbiDistributionList, String userId, String EMail) {
         this.dluId = dluId;
         this.sbiDistributionList = sbiDistributionList;
         this.userId = userId;
         this.EMail = EMail;
     }
     

    
     // Property accessors

     public Integer getDluId() {
         return this.dluId;
     }
     
     public void setDluId(Integer dluId) {
         this.dluId = dluId;
     }

     public SbiDistributionList getSbiDistributionList() {
         return this.sbiDistributionList;
     }
     
     public void setSbiDistributionList(SbiDistributionList sbiDistributionList) {
         this.sbiDistributionList = sbiDistributionList;
     }

     public String getUserId() {
         return this.userId;
     }
     
     public void setUserId(String userId) {
         this.userId = userId;
     }

     public String getEMail() {
         return this.EMail;
     }
     
     public void setEMail(String EMail) {
         this.EMail = EMail;
     }
    
}
