/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.tools.distributionlist.metadata;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * SbiDistributionList generated by hbm2java
 */

public class SbiDistributionList  implements java.io.Serializable {


    // Fields    

     private Integer dlId;
     private String name;
     private String descr;
     private Set sbiDistributionListUsers = new HashSet(0);
     private Set sbiDistributionListsObjectses = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiDistributionList() {
    }

	/** minimal constructor */
    public SbiDistributionList(Integer dlId, String name) {
        this.dlId = dlId;
        this.name = name;
    }
    
    /** full constructor */
    public SbiDistributionList(Integer dlId, String name, String descr, Set sbiDistributionListUsers, Set sbiDistributionListsObjectses) {
        this.dlId = dlId;
        this.name = name;
        this.descr = descr;
        this.sbiDistributionListUsers = sbiDistributionListUsers;
        this.sbiDistributionListsObjectses = sbiDistributionListsObjectses;
    }
    

   
    // Property accessors

    public Integer getDlId() {
        return this.dlId;
    }
    
    public void setDlId(Integer dlId) {
        this.dlId = dlId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    public Set getSbiDistributionListUsers() {
        return this.sbiDistributionListUsers;
    }
    
    public void setSbiDistributionListUsers(Set sbiDistributionListUsers) {
        this.sbiDistributionListUsers = sbiDistributionListUsers;
    }

    public Set getSbiDistributionListsObjectses() {
        return this.sbiDistributionListsObjectses;
    }
    
    public void setSbiDistributionListsObjectses(Set sbiDistributionListsObjectses) {
        this.sbiDistributionListsObjectses = sbiDistributionListsObjectses;
    }
   




}
