package it.eng.spagobi.tools.distributionlist.metadata;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3



/**
 * SbiDistributionListUser generated by hbm2java
 */

public class SbiDistributionListUser  implements java.io.Serializable {


    // Fields    

     private Integer dluId;
     private Integer listId;
     private String userId;
     private String EMail;


    // Constructors

    /** default constructor */
    public SbiDistributionListUser() {
    }

    
    /** full constructor */
    public SbiDistributionListUser(Integer dluId, Integer listId, String userId, String EMail) {
        this.dluId = dluId;
        this.listId = listId;
        this.userId = userId;
        this.EMail = EMail;
    }
    

   
    // Property accessors

    public Integer getDluId() {
        return this.dluId;
    }
    
    public void setDluId(Integer dluId) {
        this.dluId = dluId;
    }

    public Integer getListId() {
        return this.listId;
    }
    
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
   








}
