package it.eng.spagobi.tools.distributionlist.metadata;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * SbiDistributionList generated by hbm2java
 */

public class SbiDistributionList  implements java.io.Serializable {


    // Fields    

     private Integer dlId;
     private String name;
     private String descr;
     private Set sbiDistributionListsObjectses = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiDistributionList() {
    }

	/** minimal constructor */
    public SbiDistributionList(Integer dlId, String name) {
        this.dlId = dlId;
        this.name = name;
    }
    
    /** full constructor */
    public SbiDistributionList(Integer dlId, String name, String descr, Set sbiDistributionListsObjectses) {
        this.dlId = dlId;
        this.name = name;
        this.descr = descr;
        this.sbiDistributionListsObjectses = sbiDistributionListsObjectses;
    }
    

   
    // Property accessors

    public Integer getDlId() {
        return this.dlId;
    }
    
    public void setDlId(Integer dlId) {
        this.dlId = dlId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    public Set getSbiDistributionListsObjectses() {
        return this.sbiDistributionListsObjectses;
    }
    
    public void setSbiDistributionListsObjectses(Set sbiDistributionListsObjectses) {
        this.sbiDistributionListsObjectses = sbiDistributionListsObjectses;
    }
   








}
