DROP SEQUENCE SBI_CHECKS_SEQ ;
DROP SEQUENCE SBI_DOMAINS_SEQ ;
DROP SEQUENCE SBI_ENGINES_SEQ ;
DROP SEQUENCE SBI_EXT_ROLES_SEQ ;
DROP SEQUENCE SBI_FUNCTIONS_SEQ ;
DROP SEQUENCE SBI_LOV_SEQ ;
DROP SEQUENCE SBI_OBJECTS_SEQ ;
DROP SEQUENCE SBI_PARAMETERS_SEQ ;
DROP SEQUENCE SBI_PARUSE_SEQ ;
DROP SEQUENCE SBI_OBJ_PAR_SEQ ;
DROP SEQUENCE SBI_EVENTS_LOG_SEQ ;

DROP TABLE SBI_EVENTS_ROLES CASCADE CONSTRAINTS;
DROP TABLE SBI_EVENTS_LOG CASCADE CONSTRAINTS;
DROP TABLE SBI_EVENTS CASCADE CONSTRAINTS;
DROP TABLE SBI_SUBREPORTS CASCADE CONSTRAINTS;
DROP TABLE SBI_OBJ_PARUSE CASCADE CONSTRAINTS;
DROP TABLE SBI_PARUSE_CK CASCADE CONSTRAINTS;
DROP TABLE SBI_PARUSE_DET CASCADE CONSTRAINTS;
DROP TABLE SBI_PARUSE CASCADE CONSTRAINTS;
DROP TABLE SBI_FUNC_ROLE CASCADE CONSTRAINTS;
DROP TABLE SBI_OBJ_FUNC CASCADE CONSTRAINTS;
DROP TABLE SBI_FUNCTIONS CASCADE CONSTRAINTS;
DROP TABLE SBI_CHECKS CASCADE CONSTRAINTS;
DROP TABLE SBI_OBJ_PAR CASCADE CONSTRAINTS;
DROP TABLE SBI_PARAMETERS CASCADE CONSTRAINTS;
DROP TABLE SBI_OBJ_STATE CASCADE CONSTRAINTS;
DROP TABLE SBI_OBJECTS CASCADE CONSTRAINTS;
DROP TABLE SBI_EXT_ROLES CASCADE CONSTRAINTS;
DROP TABLE SBI_LOV CASCADE CONSTRAINTS;
DROP TABLE SBI_ENGINES CASCADE CONSTRAINTS;
DROP TABLE SBI_DOMAINS CASCADE CONSTRAINTS;


