ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN OWNER Varchar(50);
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN ISPUBLIC TINYINT;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN CREATION_DATE TIMESTAMP; -- NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN LAST_CHANGE_DATE TIMESTAMP;  --NOT NULL Default CURRENT_TIMESTAMP;
ALTER TABLE SBI_SUBOBJECTS MODIFY COLUMN DESCRIPTION VARCHAR(1000) DEFAULT NULL;
ALTER TABLE SBI_DATA_SET` ADD COLUMN DS_METADATA VARCHAR(2000) DEFAULT NULL;