package it.eng.spagobi.kpi.config.metadata;
// Generated 5-nov-2008 17.16.35 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.kpi.threshold.metadata.SbiThreshold;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiKpiInstance generated by hbm2java
 */

public class SbiKpiInstance  implements java.io.Serializable {


    // Fields    

     private Integer idKpiInstance;
     private SbiKpi sbiKpi;
     private SbiThreshold sbiThreshold;
     private SbiMeasureUnit sbiMeasureUnit;
     private double weight;
     private Set sbiKpiPeriodicities = new HashSet(0);
     private Set sbiKpiModelInsts = new HashSet(0);
     private Set sbiKpiInstanceHistories = new HashSet(0);
     private Set sbiKpiValues = new HashSet(0);
     private Set sbiAlarms = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiKpiInstance() {
    }

	/** minimal constructor */
    public SbiKpiInstance(Integer idKpiInstance, SbiKpi sbiKpi, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit) {
        this.idKpiInstance = idKpiInstance;
        this.sbiKpi = sbiKpi;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
    }
    
    /** full constructor */
    public SbiKpiInstance(Integer idKpiInstance, SbiKpi sbiKpi, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit, double weight, Set sbiKpiPeriodicities, Set sbiKpiModelInsts, Set sbiKpiInstanceHistories, Set sbiKpiValues, Set sbiAlarms) {
        this.idKpiInstance = idKpiInstance;
        this.sbiKpi = sbiKpi;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
        this.weight = weight;
        this.sbiKpiPeriodicities = sbiKpiPeriodicities;
        this.sbiKpiModelInsts = sbiKpiModelInsts;
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
        this.sbiKpiValues = sbiKpiValues;
        this.sbiAlarms = sbiAlarms;
    }
    

   
    // Property accessors

    public Integer getIdKpiInstance() {
        return this.idKpiInstance;
    }
    
    public void setIdKpiInstance(Integer idKpiInstance) {
        this.idKpiInstance = idKpiInstance;
    }

    public SbiKpi getSbiKpi() {
        return this.sbiKpi;
    }
    
    public void setSbiKpi(SbiKpi sbiKpi) {
        this.sbiKpi = sbiKpi;
    }

    public SbiThreshold getSbiThreshold() {
        return this.sbiThreshold;
    }
    
    public void setSbiThreshold(SbiThreshold sbiThreshold) {
        this.sbiThreshold = sbiThreshold;
    }

    public SbiMeasureUnit getSbiMeasureUnit() {
        return this.sbiMeasureUnit;
    }
    
    public void setSbiMeasureUnit(SbiMeasureUnit sbiMeasureUnit) {
        this.sbiMeasureUnit = sbiMeasureUnit;
    }

    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }

    public Set getSbiKpiPeriodicities() {
        return this.sbiKpiPeriodicities;
    }
    
    public void setSbiKpiPeriodicities(Set sbiKpiPeriodicities) {
        this.sbiKpiPeriodicities = sbiKpiPeriodicities;
    }

    public Set getSbiKpiModelInsts() {
        return this.sbiKpiModelInsts;
    }
    
    public void setSbiKpiModelInsts(Set sbiKpiModelInsts) {
        this.sbiKpiModelInsts = sbiKpiModelInsts;
    }

    public Set getSbiKpiInstanceHistories() {
        return this.sbiKpiInstanceHistories;
    }
    
    public void setSbiKpiInstanceHistories(Set sbiKpiInstanceHistories) {
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
    }

    public Set getSbiKpiValues() {
        return this.sbiKpiValues;
    }
    
    public void setSbiKpiValues(Set sbiKpiValues) {
        this.sbiKpiValues = sbiKpiValues;
    }

    public Set getSbiAlarms() {
        return this.sbiAlarms;
    }
    
    public void setSbiAlarms(Set sbiAlarms) {
        this.sbiAlarms = sbiAlarms;
    }
   








}
