package it.eng.spagobi.kpi.config.metadata;
// Generated 5-nov-2008 17.16.36 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.kpi.threshold.metadata.SbiThreshold;

import java.util.Date;


/**
 * SbiKpiInstanceHistory generated by hbm2java
 */

public class SbiKpiInstanceHistory  implements java.io.Serializable {


    // Fields    

     private Integer idKpiInstanceHistory;
     private SbiKpiInstance sbiKpiInstance;
     private SbiThreshold sbiThreshold;
     private SbiMeasureUnit sbiMeasureUnit;
     private double weight;
     private Date date;


    // Constructors

    /** default constructor */
    public SbiKpiInstanceHistory() {
    }

	/** minimal constructor */
    public SbiKpiInstanceHistory(Integer idKpiInstanceHistory, SbiKpiInstance sbiKpiInstance, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit) {
        this.idKpiInstanceHistory = idKpiInstanceHistory;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
    }
    
    /** full constructor */
    public SbiKpiInstanceHistory(Integer idKpiInstanceHistory, SbiKpiInstance sbiKpiInstance, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit, double weight, Date date) {
        this.idKpiInstanceHistory = idKpiInstanceHistory;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
        this.weight = weight;
        this.date = date;
    }
    

   
    // Property accessors

    public Integer getIdKpiInstanceHistory() {
        return this.idKpiInstanceHistory;
    }
    
    public void setIdKpiInstanceHistory(Integer idKpiInstanceHistory) {
        this.idKpiInstanceHistory = idKpiInstanceHistory;
    }

    public SbiKpiInstance getSbiKpiInstance() {
        return this.sbiKpiInstance;
    }
    
    public void setSbiKpiInstance(SbiKpiInstance sbiKpiInstance) {
        this.sbiKpiInstance = sbiKpiInstance;
    }

    public SbiThreshold getSbiThreshold() {
        return this.sbiThreshold;
    }
    
    public void setSbiThreshold(SbiThreshold sbiThreshold) {
        this.sbiThreshold = sbiThreshold;
    }

    public SbiMeasureUnit getSbiMeasureUnit() {
        return this.sbiMeasureUnit;
    }
    
    public void setSbiMeasureUnit(SbiMeasureUnit sbiMeasureUnit) {
        this.sbiMeasureUnit = sbiMeasureUnit;
    }

    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
   








}
