package it.eng.spagobi.kpi.config.metadata;

import java.util.HashSet;
// Generated 5-nov-2008 17.16.37 by Hibernate Tools 3.1.0 beta3
import java.util.Set;



/**
 * SbiKpiPeriodicity generated by hbm2java
 */

public class SbiKpiPeriodicity  implements java.io.Serializable {


    // Fields    

     private Integer idKpiInstancePeriod;
     private Integer value;
     private Set sbiKpiInstances = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiKpiPeriodicity() {
    }

	/** minimal constructor */
    public SbiKpiPeriodicity(Integer idKpiInstancePeriod) {
        this.idKpiInstancePeriod = idKpiInstancePeriod;
    }
    
    /** full constructor */
    public SbiKpiPeriodicity(Integer idKpiInstancePeriod,  Integer value, Set sbiKpiInstances) {
        this.idKpiInstancePeriod = idKpiInstancePeriod;
        this.sbiKpiInstances = sbiKpiInstances;
        this.value = value;
    }
    

   
    // Property accessors

    public Integer getIdKpiInstancePeriod() {
        return this.idKpiInstancePeriod;
    }
    
    public void setIdKpiInstancePeriod(Integer idKpiInstancePeriod) {
        this.idKpiInstancePeriod = idKpiInstancePeriod;
    }

    public Set getSbiKpiInstances() {
        return this.sbiKpiInstances;
    }
    
    public void setSbiKpiInstances(Set sbiKpiInstances) {
        this.sbiKpiInstances = sbiKpiInstances;
    }

    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }
   








}
