INSERT INTO SBI_DOMAINS (DOMAIN_CD, DOMAIN_NM, VALUE_CD, VALUE_NM, VALUE_DS) VALUES ('MODEL_ROOT', 'Model root type', 'GENERIC_ROOT', 'Generic root', '');

INSERT INTO SBI_DOMAINS (DOMAIN_CD, DOMAIN_NM, VALUE_CD, VALUE_NM, VALUE_DS) VALUES ('MODEL_NODE', 'Model node type', 'GENERIC_NODE', 'Generic Node', '');

