/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiParuseCkId generated by hbm2java
 */
public class SbiParuseCkId  implements java.io.Serializable {

    // Fields    

     private SbiParuse sbiParuse;
     private SbiChecks sbiChecks;


    // Constructors

    /** default constructor */
    public SbiParuseCkId() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public SbiParuse getSbiParuse() {
        return this.sbiParuse;
    }
    
    public void setSbiParuse(SbiParuse sbiParuse) {
        this.sbiParuse = sbiParuse;
    }

    /**
     * 
     */
    public SbiChecks getSbiChecks() {
        return this.sbiChecks;
    }
    
    public void setSbiChecks(SbiChecks sbiChecks) {
        this.sbiChecks = sbiChecks;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiParuseCkId) ) return false;
		 SbiParuseCkId castOther = ( SbiParuseCkId ) other; 
         
		 return (this.getSbiParuse()==castOther.getSbiParuse()) || ( this.getSbiParuse()!=null && castOther.getSbiParuse()!=null && this.getSbiParuse().equals(castOther.getSbiParuse()) )
 && (this.getSbiChecks()==castOther.getSbiChecks()) || ( this.getSbiChecks()!=null && castOther.getSbiChecks()!=null && this.getSbiChecks().equals(castOther.getSbiChecks()) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSbiParuse().hashCode();
         result = 37 * result + this.getSbiChecks().hashCode();
         return result;
   }   


}