package it.eng.spagobi.kpi.config.metadata;
// Generated 5-nov-2008 17.16.36 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.kpi.threshold.metadata.SbiThreshold;
import it.eng.spagobi.tools.dataset.metadata.SbiDataSetConfig;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiKpi generated by hbm2java
 */

public class SbiKpi  implements java.io.Serializable {


    // Fields    

     private Integer kpiId;
     private SbiKpi sbiKpi;
     private SbiDataSetConfig sbiDataSet;
     private SbiThreshold sbiThreshold;
     private SbiMeasureUnit sbiMeasureUnit;
     private String name;
     private String documentLabel;
     private String code;
     private String metric;
     private String description;
     private Double weight;
     private Character flgIsFather;
     private Set sbiKpiModels = new HashSet(0);
     private Set sbiKpis = new HashSet(0);
     private Set sbiKpiInstances = new HashSet(0);
     private Set sbiKpiRoles = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiKpi() {
    }

	/** minimal constructor */
    public SbiKpi(Integer kpiId, String name) {
        this.kpiId = kpiId;
        this.name = name;
    }
    
    /** full constructor */
    public SbiKpi(Integer kpiId, SbiKpi sbiKpi, SbiDataSetConfig sbiDataSet, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit, String name, String documentLabel, String code, String metric, String description, Double weight, Character flgIsFather, Set sbiKpiModels, Set sbiKpis, Set sbiKpiInstances, Set sbiKpiRoles) {
        this.kpiId = kpiId;
        this.sbiKpi = sbiKpi;
        this.sbiDataSet = sbiDataSet;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
        this.name = name;
        this.documentLabel = documentLabel;
        this.code = code;
        this.metric = metric;
        this.description = description;
        this.weight = weight;
        this.flgIsFather = flgIsFather;
        this.sbiKpiModels = sbiKpiModels;
        this.sbiKpis = sbiKpis;
        this.sbiKpiInstances = sbiKpiInstances;
        this.sbiKpiRoles = sbiKpiRoles;
    }
    

   
    // Property accessors

    public Integer getKpiId() {
        return this.kpiId;
    }
    
    public void setKpiId(Integer kpiId) {
        this.kpiId = kpiId;
    }

    public SbiKpi getSbiKpi() {
        return this.sbiKpi;
    }
    
    public void setSbiKpi(SbiKpi sbiKpi) {
        this.sbiKpi = sbiKpi;
    }

    public SbiDataSetConfig getSbiDataSet() {
        return this.sbiDataSet;
    }
    
    public void setSbiDataSet(SbiDataSetConfig sbiDataSet) {
        this.sbiDataSet = sbiDataSet;
    }

    public SbiThreshold getSbiThreshold() {
        return this.sbiThreshold;
    }
    
    public void setSbiThreshold(SbiThreshold sbiThreshold) {
        this.sbiThreshold = sbiThreshold;
    }

    public SbiMeasureUnit getSbiMeasureUnit() {
        return this.sbiMeasureUnit;
    }
    
    public void setSbiMeasureUnit(SbiMeasureUnit sbiMeasureUnit) {
        this.sbiMeasureUnit = sbiMeasureUnit;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDocumentLabel() {
        return this.documentLabel;
    }
    
    public void setDocumentLabel(String documentLabel) {
        this.documentLabel = documentLabel;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getMetric() {
        return this.metric;
    }
    
    public void setMetric(String metric) {
        this.metric = metric;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public Character getFlgIsFather() {
        return this.flgIsFather;
    }
    
    public void setFlgIsFather(Character flgIsFather) {
        this.flgIsFather = flgIsFather;
    }

    public Set getSbiKpiModels() {
        return this.sbiKpiModels;
    }
    
    public void setSbiKpiModels(Set sbiKpiModels) {
        this.sbiKpiModels = sbiKpiModels;
    }

    public Set getSbiKpis() {
        return this.sbiKpis;
    }
    
    public void setSbiKpis(Set sbiKpis) {
        this.sbiKpis = sbiKpis;
    }

    public Set getSbiKpiInstances() {
        return this.sbiKpiInstances;
    }
    
    public void setSbiKpiInstances(Set sbiKpiInstances) {
        this.sbiKpiInstances = sbiKpiInstances;
    }

    public Set getSbiKpiRoles() {
        return this.sbiKpiRoles;
    }
    
    public void setSbiKpiRoles(Set sbiKpiRoles) {
        this.sbiKpiRoles = sbiKpiRoles;
    }
   








}
