/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.commons.metadata;


import java.util.*;




/**
 * SbiExtRoles generated by hbm2java
 */
public class SbiExtRoles  implements java.io.Serializable {

    // Fields    

     private Integer extRoleId;
     private SbiDomains roleType;
     private String roleTypeCode;
     private String code;
     private String name;
     private String descr;
     private Boolean isAbleToSeeSubobjects;
     private Boolean isAbleToSeeViewpoints;
     private Boolean isAbleToSeeSnapshots;
     private Boolean isAbleToSeeNotes;
     private Boolean isAbleToSendMail;
     private Boolean isAbleToSaveIntoPersonalFolder;
     private Boolean isAbleToSaveRememberMe;
     private Boolean isAbleToSeeMetadata;
     private Set sbiFuncRoles;
     private Set sbiParuseDets;


    // Constructors

    /** default constructor */
    public SbiExtRoles() {
    }
    
    /** constructor with id */
    public SbiExtRoles(Integer extRoleId) {
        this.extRoleId = extRoleId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getExtRoleId() {
        return this.extRoleId;
    }
    
    public void setExtRoleId(Integer extRoleId) {
        this.extRoleId = extRoleId;
    }

    /**
     * 
     */
    public SbiDomains getRoleType() {
        return this.roleType;
    }
    
    public void setRoleType(SbiDomains sbiDomains) {
        this.roleType = sbiDomains;
    }

    /**
     * 
     */
    public String getRoleTypeCode() {
        return this.roleTypeCode;
    }
    
    public void setRoleTypeCode(String roleTypeCd) {
        this.roleTypeCode = roleTypeCd;
    }

    /**
     * 
     */
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * 
     */
    public Set getSbiFuncRoles() {
        return this.sbiFuncRoles;
    }
    
    public void setSbiFuncRoles(Set sbiFuncRoles) {
        this.sbiFuncRoles = sbiFuncRoles;
    }

    /**
     * 
     */
    public Set getSbiParuseDets() {
        return this.sbiParuseDets;
    }
    
    public void setSbiParuseDets(Set sbiParuseDets) {
        this.sbiParuseDets = sbiParuseDets;
    }

	public Boolean getIsAbleToSeeSubobjects() {
		return isAbleToSeeSubobjects;
	}

	public void setIsAbleToSeeSubobjects(Boolean isAbleToSeeSubobjects) {
		this.isAbleToSeeSubobjects = isAbleToSeeSubobjects;
	}

	public Boolean getIsAbleToSeeViewpoints() {
		return isAbleToSeeViewpoints;
	}

	public void setIsAbleToSeeViewpoints(Boolean isAbleToSeeViewpoints) {
		this.isAbleToSeeViewpoints = isAbleToSeeViewpoints;
	}

	public Boolean getIsAbleToSeeSnapshots() {
		return isAbleToSeeSnapshots;
	}

	public void setIsAbleToSeeSnapshots(Boolean isAbleToSeeSnapshots) {
		this.isAbleToSeeSnapshots = isAbleToSeeSnapshots;
	}

	public Boolean getIsAbleToSeeNotes() {
		return isAbleToSeeNotes;
	}

	public void setIsAbleToSeeNotes(Boolean isAbleToSeeNotes) {
		this.isAbleToSeeNotes = isAbleToSeeNotes;
	}

	public Boolean getIsAbleToSendMail() {
		return isAbleToSendMail;
	}

	public void setIsAbleToSendMail(Boolean isAbleToSendMail) {
		this.isAbleToSendMail = isAbleToSendMail;
	}

	public Boolean getIsAbleToSaveIntoPersonalFolder() {
		return isAbleToSaveIntoPersonalFolder;
	}

	public void setIsAbleToSaveIntoPersonalFolder(
			Boolean isAbleToSaveIntoPersonalFolder) {
		this.isAbleToSaveIntoPersonalFolder = isAbleToSaveIntoPersonalFolder;
	}

	public Boolean getIsAbleToSaveRememberMe() {
		return isAbleToSaveRememberMe;
	}

	public void setIsAbleToSaveRememberMe(Boolean isAbleToSaveRememberMe) {
		this.isAbleToSaveRememberMe = isAbleToSaveRememberMe;
	}

	public Boolean getIsAbleToSeeMetadata() {
		return isAbleToSeeMetadata;
	}

	public void setIsAbleToSeeMetadata(Boolean isAbleToSeeMetadata) {
		this.isAbleToSeeMetadata = isAbleToSeeMetadata;
	}



}