/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;





/**
 * SbiLov generated by hbm2java
 */
public class SbiLov  implements java.io.Serializable {

    // Fields    

     private Integer lovId;
     private SbiDomains inputType;
     private String inputTypeCd;
     private String defaultVal;
     private String label;
     private String descr;
     private String profileAttr;
     private String lovProvider;
     private String name;


    // Constructors

    /** default constructor */
    public SbiLov() {
    }
    
    /** constructor with id */
    public SbiLov(Integer lovId) {
        this.lovId = lovId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getLovId() {
        return this.lovId;
    }
    
    public void setLovId(Integer lovId) {
        this.lovId = lovId;
    }


    /**
     * 
     */
    public String getInputTypeCd() {
        return this.inputTypeCd;
    }
    
    public void setInputTypeCd(String inputTypeCd) {
        this.inputTypeCd = inputTypeCd;
    }

    /**
     * 
     */
    public String getDefaultVal() {
        return this.defaultVal;
    }
    
    public void setDefaultVal(String defaultVal) {
        this.defaultVal = defaultVal;
    }

    /**
     * 
     */
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * 
     */
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * 
     */
    public String getProfileAttr() {
        return this.profileAttr;
    }
    
    public void setProfileAttr(String profileAttr) {
        this.profileAttr = profileAttr;
    }

    /**
     * 
     */
    public String getLovProvider() {
        return this.lovProvider;
    }
    
    public void setLovProvider(String lovProvider) {
        this.lovProvider = lovProvider;
    }


	public SbiDomains getInputType() {
		return inputType;
	}
	public void setInputType(SbiDomains inputType) {
		this.inputType = inputType;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}