/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiObjPar generated by hbm2java
 */
public class SbiObjPar  implements java.io.Serializable {

    // Fields    

     private SbiObjParId id;
     private Short reqFl;
     private Short modFl;
     private Short viewFl;
     private Short multFl;
     private String label;
     private String parurlNm;


    // Constructors

    /** default constructor */
    public SbiObjPar() {
    }
    
    /** constructor with id */
    public SbiObjPar(SbiObjParId id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public SbiObjParId getId() {
        return this.id;
    }
    
    public void setId(SbiObjParId id) {
        this.id = id;
    }

    /**
     * 
     */
    public Short getReqFl() {
        return this.reqFl;
    }
    
    public void setReqFl(Short reqFl) {
        this.reqFl = reqFl;
    }

    /**
     * 
     */
    public Short getModFl() {
        return this.modFl;
    }
    
    public void setModFl(Short modFl) {
        this.modFl = modFl;
    }

    /**
     * 
     */
    public Short getViewFl() {
        return this.viewFl;
    }
    
    public void setViewFl(Short viewFl) {
        this.viewFl = viewFl;
    }

    /**
     * 
     */
    public Short getMultFl() {
        return this.multFl;
    }
    
    public void setMultFl(Short multFl) {
        this.multFl = multFl;
    }

    /**
     * 
     */
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * 
     */
    public String getParurlNm() {
        return this.parurlNm;
    }
    
    public void setParurlNm(String parurlNm) {
        this.parurlNm = parurlNm;
    }



}