#!/usr/bin/perl

=head1 
Process , version , status .
Author: 
Purpose: 

=cut




my $_licence = <<'END_OF_LICENCE';

  Copyright (c) 2005-2006, Talend SA

  This source code has been automatically generated by talend
  OpenStudio / ProcessDesigner (CodeGenerator version 1.1.2.r2022).
  You can find more information about talend products at www.talend.com.
  You may distribute this code under the terms of either the GNU General
  Public License or under the Artistic License just like Perl itself.

END_OF_LICENCE

# print $_licence;

use Getopt::Long;
use Time::HiRes qw/gettimeofday tv_interval/;
my %opt = ();
GetOptions(
    \%opt,
    qw/context=s stat_port=i trace_port=i watch/
);

our %_context;
our %_globals;

$_globals{job_name} = 'HelloWorld';
$_globals{start} = [gettimeofday];

if (defined $opt{context}) {
#     print(
#         'tsInfo>  Running process with context: ',
#         $opt{context},
#         ' (./tUser/parameters_', $opt{context}, '.pl)',
#         "\n\n"
#     );

    require $opt{context};
}

use SPAGOBITALENDTEST__Date;
use SPAGOBITALENDTEST__Misc;
use SPAGOBITALENDTEST__String;


use constant true   => 1;
use constant false  => 0;
use constant null   => undef;

$SIG{__DIE__} = \&global_die_catcher;
$current_component=undef;

sub global_die_catcher {
    if (defined $current_component) {
        my $dying_component = $current_component;

        our $_globals;

        my $exception = $_[0];
        chomp($exception);

        $_globals{$dying_component}{ERROR_MESSAGE}      = $exception;
        $_globals{$dying_component}{PERL_ERROR_MESSAGE} = $!;
        $_globals{$dying_component}{PERL_ERROR_CODE}    = int($!);

        if (defined &main::tCatcher_1_subprocess) {
            tCatcher_1_subprocess(
                type => 'Perl die',
                origin => $dying_component,
                priority => 100,
                error_message => $_globals{$dying_component}{ERROR_MESSAGE},
                perl_error_message => $_globals{$dying_component}{PERL_ERROR_MESSAGE},
                perl_error_code => $_globals{$dying_component}{PERL_ERROR_CODE},
            );
        }

        no strict 'refs';
        &{$dying_component.'_error'}();
    }
}
sub tMsgBox_1_error() {
}

# +-------------------------------------------------------------------------+
# | [subprocess header] starts here                                         |
# +-------------------------------------------------------------------------+ 

	sub tMsgBox_1_subprocess  {
# +-------------------------------------------------------------------------+
# | [subprocess header] stops here                                          |
# +-------------------------------------------------------------------------+ 
# +-------------------------------------------------------------------------+
# | [tMsgBox_1 begin ] start
# +-------------------------------------------------------------------------+ 

$current_component="tMsgBox_1";



=head1 tMsgBox tMsgBox_1

=cut

$_globals{tMsgBox_1}{OK} = false;





# +-------------------------------------------------------------------------+
# | [tMsgBox_1 begin ] stop
# +-------------------------------------------------------------------------+ 
# +-------------------------------------------------------------------------+
# | [tMsgBox_1 main ] start
# +-------------------------------------------------------------------------+ 

$current_component="tMsgBox_1";




my $title = 'Talend Open Studio';
if ($title eq '') {
    $title = 'Default message';
}

if (eval "require Win32") {
    Win32::MsgBox(
        'Hello ' . $_context{userName} . '!!! Process has been executed succesfully in ' . $_context{contextName} . ' context.',
        Win32::MB_ICONINFORMATION | 0,
        $title
    );
}
elsif (eval "require Text::ASCIITable") {
    my $t = Text::ASCIITable->new();
    $t->setCols($title);
    $t->alignColName($title, 'center');
    $t->setColWidth($title,80);
    $t->addRow('Hello ' . $_context{userName} . '!!! Process has been executed succesfully in ' . $_context{contextName} . ' context.');
    $t->addRowLine();
    print $t;
}
else {
    print "\n";
    print "=========== ", $title, " ============\n";
    print 'Hello ' . $_context{userName} . '!!! Process has been executed succesfully in ' . $_context{contextName} . ' context.', "\n";
    print "===========", "=" x (length($title) + 2), "============\n";
}


# +-------------------------------------------------------------------------+
# | [tMsgBox_1 main ] stop
# +-------------------------------------------------------------------------+ 
# +-------------------------------------------------------------------------+
# | [                                                                       |
# +-------------------------------------------------------------------------+ 

# +-------------------------------------------------------------------------+
# | [tMsgBox_1 end ] start
# +-------------------------------------------------------------------------+ 

$current_component="tMsgBox_1";




$_globals{tMsgBox_1}{OK} = true;


# +-------------------------------------------------------------------------+
# | [tMsgBox_1 end ] stop
# +-------------------------------------------------------------------------+ 
# +-------------------------------------------------------------------------+
# | [subprocess footer] starts here                                         |
# +-------------------------------------------------------------------------+ 
	}
# +-------------------------------------------------------------------------+
# | [subprocess footer] stops here                                          |
# +-------------------------------------------------------------------------+ 

# +-------------------------------------------------------------------------+
# | [footer] starts here                                                    |
# +-------------------------------------------------------------------------+ 



tMsgBox_1_subprocess();


$_globals{stop} = [gettimeofday];

$_globals{duration} = sprintf(
    '%.1f', 
    tv_interval(
        $_globals{start},
        $_globals{stop}
    )
);


if (defined $opt{watch}) {
    printf(
        "===\nexecution time: %s seconds\n===\n",
        $_globals{duration}
    );
}

# +-------------------------------------------------------------------------+
# | [footer] stops here                                                     |
# +-------------------------------------------------------------------------+ 
# +-------------------------------------------------------------------------+
#      6744 characters generated by Talend OpenStudio 
#      on the 7 maggio 2007 9.51.08 LKT
# +-------------------------------------------------------------------------+