/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiObjStateId generated by hbm2java
 */
public class SbiObjStateId  implements java.io.Serializable {

    // Fields    

     private SbiDomains sbiDomains;
     private SbiObjects sbiObjects;
     private Date startDt;


    // Constructors

    /** default constructor */
    public SbiObjStateId() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public SbiDomains getSbiDomains() {
        return this.sbiDomains;
    }
    
    public void setSbiDomains(SbiDomains sbiDomains) {
        this.sbiDomains = sbiDomains;
    }

    /**
     * 
     */
    public SbiObjects getSbiObjects() {
        return this.sbiObjects;
    }
    
    public void setSbiObjects(SbiObjects sbiObjects) {
        this.sbiObjects = sbiObjects;
    }

    /**
     * 
     */
    public Date getStartDt() {
        return this.startDt;
    }
    
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiObjStateId) ) return false;
		 SbiObjStateId castOther = ( SbiObjStateId ) other; 
         
		 return (this.getSbiDomains()==castOther.getSbiDomains()) || ( this.getSbiDomains()!=null && castOther.getSbiDomains()!=null && this.getSbiDomains().equals(castOther.getSbiDomains()) )
 && (this.getSbiObjects()==castOther.getSbiObjects()) || ( this.getSbiObjects()!=null && castOther.getSbiObjects()!=null && this.getSbiObjects().equals(castOther.getSbiObjects()) )
 && (this.getStartDt()==castOther.getStartDt()) || ( this.getStartDt()!=null && castOther.getStartDt()!=null && this.getStartDt().equals(castOther.getStartDt()) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSbiDomains().hashCode();
         result = 37 * result + this.getSbiObjects().hashCode();
         result = 37 * result + this.getStartDt().hashCode();
         return result;
   }   


}