ALTER TABLE SBI_DATA_SOURCE ALTER COLUMN URL_CONNECTION VARCHAR(500);\p\g 

ALTER TABLE SBI_ALARM ALTER COLUMN LABEL VARCHAR(50) NOT NULL;
Create UNIQUE Index label_unique  ON SBI_ALARM (LABEL )  ;\p\g

Create UNIQUE Index name_unique  ON SBI_ALARM_CONTACT (NAME )  ;\p\g

Create UNIQUE Index code_unique  ON SBI_KPI (code )  ;\p\g

Create UNIQUE Index unique_kpi_model_cd  ON SBI_KPI_MODEL (KPI_MODEL_CD )  ;\p\g

Create UNIQUE Index name_unique  ON SBI_KPI_PERIODICITY (name )  ;\p\g

ALTER TABLE SBI_THRESHOLD ALTER COLUMN code VARCHAR(45) NOT NULL;\p\g
Create UNIQUE Index code_unique  ON SBI_THRESHOLD (code )  ;\p\g

ALTER TABLE SBI_THRESHOLD_VALUE ALTER COLUMN label VARCHAR(20) NOT NULL;
Create UNIQUE Index label_thId_unique  ON SBI_THRESHOLD_VALUE (label, THRESHOLD_ID )  ;\p\g

Create UNIQUE Index unique_resource_name  ON SBI_RESOURCES (RESOURCE_NAME )  ;\p\g

ALTER TABLE SBI_KPI_MODEL ALTER COLUMN KPI_MODEL_CD VARCHAR(40) NOT NULL;\p\g

ALTER TABLE SBI_KPI_PERIODICITY ALTER COLUMN name VARCHAR(400) NOT NULL;\p\g

ALTER TABLE SBI_RESOURCES ALTER COLUMN RESOURCE_NAME VARCHAR(40) NOT NULL;\p\g

Create table SBI_EXPORTERS (
	ENGINE_ID Integer NOT NULL,
	DOMAIN_ID Integer NOT NULL,
	DEFAULT_VALUE Boolean,
	UNIQUE(ENGINE_ID, DOMAIN_ID)
Primary Key (ENGINE_ID,DOMAIN_ID)
) ;\p\g


ALTER TABLE SBI_EXPORTERS ADD CONSTRAINT FK_sbi_exporters_1 FOREIGN KEY ( DOMAIN_ID ) REFERENCES SBI_DOMAINS ( VALUE_ID );\p\g
ALTER TABLE SBI_EXPORTERS ADD CONSTRAINT FK_sbi_exporters_2 FOREIGN KEY ( ENGINE_ID ) REFERENCES SBI_ENGINES ( ENGINE_ID );\p\g


/*adds record for exporter functionality*/ 
Insert into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('PDF','PDF','EXPORT_TYPE','Exporters type','Exporters type');\p\g
Insert into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('XLS','XLS','EXPORT_TYPE','Exporters type','Exporters type');\p\g
Insert into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('JPG','JPG','EXPORT_TYPE','Exporters type','Exporters type');\p\g
Insert into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('PPT','PPT','EXPORT_TYPE','Exporters type','Exporters type');\p\g

commit;