ALTER TABLE SBI_DATA_SOURCE ADD COLUMN ATTR_SCHEMA VARCHAR(45) NULL;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN XML_DATA TEXT;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN MULTI_SCHEMA TINYINT; -- DEFAULT 0;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN BUILD_QBE_QUERY TINYINT; -- DEFAULT 1;