/* Modifies to add Model Label */
ALTER TABLE SBI_KPI_MODEL ADD KPI_MODEL_LBL VARCHAR(100) NOT NULL;
UPDATE SBI_KPI_MODEL SET KPI_MODEL_LBL = KPI_MODEL_CD
ALTER TABLE SBI_KPI_MODEL DROP INDEX UNIQUE_KPI_MODEL_CD;
ALTER TABLE SBI_KPI_MODEL ADD UNIQUE INDEX UNIQUE_LABEL(KPI_MODEL_LBL);
ALTER TABLE SBI_KPI_MODEL ADD UNIQUE INDEX UNIQUE_PAR_ID_CD(KPI_PARENT_MODEL_ID, KPI_MODEL_CD);

/* Modifies SBI_THRESHOLD_VALUE TABLE to add the selection to specify if the range is open or closed */
ALTER TABLE SBI_THRESHOLD_VALUE ADD MIN_CLOSED BOOLEAN;
ALTER TABLE SBI_THRESHOLD_VALUE ADD MAX_CLOSED BOOLEAN;
ALTER TABLE SBI_THRESHOLD_VALUE ADD TH_VALUE DOUBLE;

/* Modifies SBI_KPI_MODEL_INST to specify a KPI INSTANCE or a MODEL INSTANCE LABEL */
ALTER TABLE SBI_KPI_MODEL_INST ADD MODELUUID VARCHAR(400);