/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiChecks generated by hbm2java
 */
public class SbiChecks  implements java.io.Serializable {

    // Fields    

     private Integer checkId;
     private SbiDomains checkType;
     private String valueTypeCd;
     private String value1;
     private String value2;
     private String label;
     private String name;
     private String descr;
     


    // Constructors

    /** default constructor */
    public SbiChecks() {
    }
    
    /** constructor with id */
    public SbiChecks(Integer checkId) {
        this.checkId = checkId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getCheckId() {
        return this.checkId;
    }
    
    public void setCheckId(Integer checkId) {
        this.checkId = checkId;
    }

    /**
     * 
     */
    public SbiDomains getCheckType() {
        return this.checkType;
    }
    
    public void setCheckType(SbiDomains sbiDomains) {
        this.checkType = sbiDomains;
    }

    /**
     * 
     */
    public String getValueTypeCd() {
        return this.valueTypeCd;
    }
    
    public void setValueTypeCd(String valueTypeCd) {
        this.valueTypeCd = valueTypeCd;
    }

    /**
     * 
     */
    public String getValue1() {
        return this.value1;
    }
    
    public void setValue1(String value1) {
        this.value1 = value1;
    }

    /**
     * 
     */
    public String getValue2() {
        return this.value2;
    }
    
    public void setValue2(String value2) {
        this.value2 = value2;
    }

    /**
     * 
     */
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * 
     */
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    



	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}