/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiParameters generated by hbm2java
 */
public class SbiParameters  implements java.io.Serializable {

    // Fields    

     private Integer parId;
     private SbiDomains parameterType;
     private Short length;
     private String parameterTypeCode;
     private String label;
     private String name;
     private String mask;
     private String descr;
     private Set sbiParuses;
     private Set sbiObjPars;
     private Short functionalFlag;

    // Constructors

    /** default constructor */
    public SbiParameters() {
    }
    
    /** constructor with id */
    public SbiParameters(Integer parId) {
        this.parId = parId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getParId() {
        return this.parId;
    }
    
    public void setParId(Integer parId) {
        this.parId = parId;
    }

    /**
     * 
     */
    public SbiDomains getParameterType() {
        return this.parameterType;
    }
    
    public void setParameterType(SbiDomains sbiDomains) {
        this.parameterType = sbiDomains;
    }

    /**
     * 
     */
    public Short getLength() {
        return this.length;
    }
    
    public void setLength(Short length) {
        this.length = length;
    }

    /**
     * 
     */
    public String getParameterTypeCode() {
        return this.parameterTypeCode;
    }
    
    public void setParameterTypeCode(String parTypeCd) {
        this.parameterTypeCode = parTypeCd;
    }

    /**
     * 
     */
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * 
     */
    public String getMask() {
        return this.mask;
    }
    
    public void setMask(String mask) {
        this.mask = mask;
    }

    /**
     * 
     */
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * 
     */
    public Set getSbiParuses() {
        return this.sbiParuses;
    }
    
    public void setSbiParuses(Set sbiParuses) {
        this.sbiParuses = sbiParuses;
    }

    /**
     * 
     */
    public Set getSbiObjPars() {
        return this.sbiObjPars;
    }
    
    public void setSbiObjPars(Set sbiObjPars) {
        this.sbiObjPars = sbiObjPars;
    }



	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	public Short getFunctionalFlag() {
		return functionalFlag;
	}

	public void setFunctionalFlag(Short functionalFlag) {
		this.functionalFlag = functionalFlag;
	}
	
}