/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.Date;



/**
 * SbiViewpoints generated by hbm2java
 */

public class SbiViewpoints  implements java.io.Serializable {


    // Fields    

     private Integer vpId;
     //private Integer biobjId;
     private SbiObjects sbiObject;
     private String vpOwner;
     private String vpName;
     private String vpDesc;
     private String vpScope;
     private String vpValueParams;
     private Date 	vpCreationDate;


    // Constructors

    /** default constructor */
    public SbiViewpoints() {
    }

	/** minimal constructor */
    public SbiViewpoints(Integer vpId, Integer biobjId, String vpOwner, String vpName, String vpScope, Date vpCreationDate) {
        this.vpId = vpId;
        //this.biobjId = biobjId;
        this.vpOwner = vpOwner;
        this.vpName = vpName;
        this.vpScope = vpScope;
        this.vpCreationDate = vpCreationDate;
    }
    
    /** full constructor */
    public SbiViewpoints(Integer vpId, Integer biobjId, String vpOwner, String vpName, String vpDesc, String vpScope, String vpValueParams, Date vpCreationDate) {
        this.vpId = vpId;
        //this.biobjId = biobjId;
        this.vpOwner = vpOwner;
        this.vpName = vpName;
        this.vpDesc = vpDesc;
        this.vpScope = vpScope;
        this.vpValueParams = vpValueParams;
        this.vpCreationDate = vpCreationDate;
    }
    

   
    // Property accessors

    public Integer getVpId() {
        return this.vpId;
    }
    
    public void setVpId(Integer vpId) {
        this.vpId = vpId;
    }
/*
    public Integer getBiobjId() {
        return this.biobjId;
    }
    
    public void setBiobjId(Integer biobjId) {
        this.biobjId = biobjId;
    }
*/
    public String getVpName() {
        return this.vpName;
    }
    
    public void setVpName(String vpName) {
        this.vpName = vpName;
    }

    public String getVpDesc() {
        return this.vpDesc;
    }
    
    public void setVpDesc(String vpDesc) {
        this.vpDesc = vpDesc;
    }

    public String getVpScope() {
        return this.vpScope;
    }
    
    public void setVpScope(String vpScope) {
        this.vpScope = vpScope;
    }

    public String getVpValueParams() {
        return this.vpValueParams;
    }
    
    public void setVpValueParams(String vpValueParams) {
        this.vpValueParams = vpValueParams;
    }
	public Date getVpCreationDate() {
		return this.vpCreationDate;
	}

	public void setVpCreationDate(Date date) {
		this.vpCreationDate = date;
	}

	/**
	 * @return the vpOwner
	 */
	public String getVpOwner() {
		return vpOwner;
	}

	/**
	 * @param vpOwner the vpOwner to set
	 */
	public void setVpOwner(String vpOwner) {
		this.vpOwner = vpOwner;
	}

	public SbiObjects getSbiObject() {
		return sbiObject;
	}

	public void setSbiObject(SbiObjects sbiObject) {
		this.sbiObject = sbiObject;
	}

}
