package it.eng.spagobi.tools.datasource.metadata;


// Generated 31-mag-2007 14.53.27 by Hibernate Tools 3.2.0.beta8

import it.eng.spagobi.commons.metadata.SbiDomains;

import java.util.Set;

/**
 * SbiGeoMaps generated by hbm2java
 */
public class SbiDataSource implements java.io.Serializable {

	// Fields    

	private int dsId;	
	
	private SbiDomains dialect;
	
	private String dialectDescr;

	private String descr;
	
	private String label;

	private String jndi;
	
	private String url_connection;
	
	private String user;
	
	private String pwd;
	
	private String driver;
	
    private Set sbiObjectses;
    
    private Set sbiEngineses;

	

	// Constructors

	/** default constructor */
	public SbiDataSource() {
	}

	/** minimal constructor 
	 * @param dsId Identifier of data source
	 * */
	public SbiDataSource(int dsId) {
		this.dsId = dsId;
	}

	/** full constructor 
	 * @param dsId Identifier of data source
	 * @param descr description of data source
	 * @param label label of data source
	 * @param jndi jndi value
	 * @param url_connection url connection value
	 * @param user user of data source
	 * @param pwd password of data source
	 * @param driver driver of data source
	 * */
	public SbiDataSource(int dsId, String descr, SbiDomains dialect, String label, String jndi, String url_connection, String user, String pwd, String driver,  Set sbiObjectses, Set sbiEngineses) {
		this.dsId = dsId;		
		this.dialect = dialect;
		this.descr = descr;
		this.label = label;
		this.jndi = jndi;
		this.url_connection = url_connection;
		this.user = user;
		this.pwd = pwd;
		this.driver = driver;
		this.sbiObjectses = sbiObjectses;
	    this.sbiEngineses = sbiEngineses;
	}

	public int getDsId() {
		return dsId;
	}

	public void setDsId(int dsId) {
		this.dsId = dsId;
	}
	
	public SbiDomains getDialect() {
        return this.dialect;
    }
    
    public void setDialect(SbiDomains dialect) {
        this.dialect = dialect;
    }
    
	public String getDialectDescr() {
        return this.dialectDescr;
    }
    
    public void setDialectDescr(String dialectDescr) {
        this.dialectDescr = dialectDescr;
    }

	public String getDescr() {
		return descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getJndi() {
		return jndi;
	}

	public void setJndi(String jndi) {
		this.jndi = jndi;
	}

	public String getUrl_connection() {
		return url_connection;
	}

	public void setUrl_connection(String url_connection) {
		this.url_connection = url_connection;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getDriver() {
		return driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}
	
	public Set getSbiObjectses() {
        return this.sbiObjectses;
    }
    
    public void setSbiObjectses(Set sbiObjectses) {
        this.sbiObjectses = sbiObjectses;
    }

    public Set getSbiEngineses() {
        return this.sbiEngineses;
    }
    
    public void setSbiEngineses(Set sbiEngineses) {
        this.sbiEngineses = sbiEngineses;
    }
}
