--Chiara 27/05/2010
ALTER TABLE SBI_RESOURCES ADD COLUMN RESOURCE_CODE VARCHAR(45);
UPDATE SBI_RESOURCES SET RESOURCE_CODE = RESOURCE_NAME;
CREATE UNIQUE INDEX UNIQUE_RES_CODE ON SBI_RESOURCES(RESOURCE_CODE);
ALTER TABLE SBI_RESOURCES ALTER COLUMN RESOURCE_CODE VARCHAR2(45) NOT NULL;
