ALTER TABLE SBI_DATA_SOURCE ADD  COLUMN ATTR_SCHEMA TYPE VARCHAR(45) DEFAULT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN MULTI_SCHEMA TYPE BOOLEAN DEFAULT FALSE;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN BUILD_QBE_QUERY TYPE BOOLEAN DEFAULT TRUE;

commit;