package it.eng.spagobi.mapcatalogue.metadata;


// Generated 31-mag-2007 14.53.27 by Hibernate Tools 3.2.0.beta8

/**
 * SbiGeoMapFeaturesId generated by hbm2java
 */
public class SbiGeoMapFeaturesId implements java.io.Serializable {

	// Fields    

	private int mapId;

	private int featureId;

	// Constructors

	/** default constructor */
	public SbiGeoMapFeaturesId() {
	}

	/** full constructor */
	public SbiGeoMapFeaturesId(int mapId, int featureId) {
		this.mapId = mapId;
		this.featureId = featureId;
	}

	// Property accessors
	public int getMapId() {
		return this.mapId;
	}

	public void setMapId(int mapId) {
		this.mapId = mapId;
	}

	public int getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(int featureId) {
		this.featureId = featureId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiGeoMapFeaturesId))
			return false;
		SbiGeoMapFeaturesId castOther = (SbiGeoMapFeaturesId) other;

		return (this.getMapId() == castOther.getMapId())
				&& (this.getFeatureId() == castOther.getFeatureId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMapId();
		result = 37 * result + this.getFeatureId();
		return result;
	}

}
