package it.eng.spagobi.wapp.metadata;
// Generated 9-apr-2008 12.18.27 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.analiticalmodel.document.metadata.SbiObjects;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiMenu generated by hbm2java
 */

public class SbiMenu  implements java.io.Serializable {


    // Fields    

     private Integer menuId;
     private SbiObjects sbiObjects;
     private String name;
     private String descr;
     private Integer parentId;
     private Set sbiMenuRoles = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiMenu() {
    }

	/** minimal constructor */
    public SbiMenu(Integer menuId) {
        this.menuId = menuId;
    }
    
    /** full constructor */
    public SbiMenu(Integer menuId, SbiObjects sbiObjects, String name, String descr, Integer parentId, Set sbiMenuRoles) {
        this.menuId = menuId;
        this.sbiObjects = sbiObjects;
        this.name = name;
        this.descr = descr;
        this.parentId = parentId;
        this.sbiMenuRoles = sbiMenuRoles;
    }
    

   
    // Property accessors

    public Integer getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    public SbiObjects getSbiObjects() {
        return this.sbiObjects;
    }
    
    public void setSbiObjects(SbiObjects sbiObjects) {
        this.sbiObjects = sbiObjects;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Set getSbiMenuRoles() {
        return this.sbiMenuRoles;
    }
    
    public void setSbiMenuRoles(Set sbiMenuRoles) {
        this.sbiMenuRoles = sbiMenuRoles;
    }
   








}
