package it.eng.spagobi.wapp.metadata;
// Generated 9-apr-2008 12.18.27 by Hibernate Tools 3.1.0 beta3



/**
 * SbiMenuRoleId generated by hbm2java
 */

public class SbiMenuRoleId  implements java.io.Serializable {


    // Fields    

     private Integer menuId;
     private Integer extRoleId;


    // Constructors

    /** default constructor */
    public SbiMenuRoleId() {
    }

    
    /** full constructor */
    public SbiMenuRoleId(Integer menuId, Integer extRoleId) {
        this.menuId = menuId;
        this.extRoleId = extRoleId;
    }
    

   
    // Property accessors

    public Integer getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    public Integer getExtRoleId() {
        return this.extRoleId;
    }
    
    public void setExtRoleId(Integer extRoleId) {
        this.extRoleId = extRoleId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiMenuRoleId) ) return false;
		 SbiMenuRoleId castOther = ( SbiMenuRoleId ) other; 
         
		 return ( (this.getMenuId()==castOther.getMenuId()) || ( this.getMenuId()!=null && castOther.getMenuId()!=null && this.getMenuId().equals(castOther.getMenuId()) ) )
 && ( (this.getExtRoleId()==castOther.getExtRoleId()) || ( this.getExtRoleId()!=null && castOther.getExtRoleId()!=null && this.getExtRoleId().equals(castOther.getExtRoleId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMenuId() == null ? 0 : this.getMenuId().hashCode() );
         result = 37 * result + ( getExtRoleId() == null ? 0 : this.getExtRoleId().hashCode() );
         return result;
   }   





}
