package it.eng.spagobi.wapp.metadata;

import it.eng.spagobi.commons.metadata.SbiExtRoles;
// Generated 9-apr-2008 12.18.26 by Hibernate Tools 3.1.0 beta3



/**
 * SbiMenuRole generated by hbm2java
 */

public class SbiMenuRole  implements java.io.Serializable {


    // Fields    

     private SbiMenuRoleId id;
     private SbiMenu sbiMenu;
     private SbiExtRoles sbiExtRoles;


    // Constructors

    /** default constructor */
    public SbiMenuRole() {
    }

    
    /** full constructor */
    public SbiMenuRole(SbiMenuRoleId id, SbiMenu sbiMenu, SbiExtRoles sbiExtRoles) {
        this.id = id;
        this.sbiMenu = sbiMenu;
        this.sbiExtRoles = sbiExtRoles;
    }
    

   
    // Property accessors

    public SbiMenuRoleId getId() {
        return this.id;
    }
    
    public void setId(SbiMenuRoleId id) {
        this.id = id;
    }

    public SbiMenu getSbiMenu() {
        return this.sbiMenu;
    }
    
    public void setSbiMenu(SbiMenu sbiMenu) {
        this.sbiMenu = sbiMenu;
    }

    public SbiExtRoles getSbiExtRoles() {
        return this.sbiExtRoles;
    }
    
    public void setSbiExtRoles(SbiExtRoles sbiExtRoles) {
        this.sbiExtRoles = sbiExtRoles;
    }
   








}
