package it.eng.spagobi.kpi.threshold.metadata;

import java.util.HashSet;
import java.util.Set;

import it.eng.spagobi.commons.metadata.SbiDomains;
// Generated 5-nov-2008 17.17.42 by Hibernate Tools 3.1.0 beta3



/**
 * SbiThresholdValue generated by hbm2java
 */

public class SbiThresholdValue  implements java.io.Serializable {


    // Fields    

     private Integer idThresholdValue;
     private SbiThreshold sbiThreshold;
     private SbiDomains sbiDomains;
     private Double minValue;
     private Double maxValue;
     private String label;
     private String colour;
     private Integer position;
     private Set sbiAlarms = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiThresholdValue() {
    }

	/** minimal constructor */
    public SbiThresholdValue(Integer idThresholdValue, SbiThreshold sbiThreshold) {
        this.idThresholdValue = idThresholdValue;
        this.sbiThreshold = sbiThreshold;
    }
    
    /** full constructor */
    public SbiThresholdValue(Integer idThresholdValue, SbiThreshold sbiThreshold, SbiDomains sbiDomains, double minValue, double maxValue, String label, String colour, Integer position, Set sbiAlarms) {
        this.idThresholdValue = idThresholdValue;
        this.sbiThreshold = sbiThreshold;
        this.sbiDomains = sbiDomains;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.label = label;
        this.colour = colour;
        this.position = position;
        this.sbiAlarms = sbiAlarms;
    }
    

   
    // Property accessors

    public Integer getIdThresholdValue() {
        return this.idThresholdValue;
    }
    
    public void setIdThresholdValue(Integer idThresholdValue) {
        this.idThresholdValue = idThresholdValue;
    }

    public SbiThreshold getSbiThreshold() {
        return this.sbiThreshold;
    }
    
    public void setSbiThreshold(SbiThreshold sbiThreshold) {
        this.sbiThreshold = sbiThreshold;
    }

    public SbiDomains getSbiDomains() {
        return this.sbiDomains;
    }
    
    public void setSbiDomains(SbiDomains sbiDomains) {
        this.sbiDomains = sbiDomains;
    }

    public Double getMinValue() {
        return this.minValue;
    }
    
    public void setMinValue(Double minValue) {
        this.minValue = minValue;
    }

    public Double getMaxValue() {
        return this.maxValue;
    }
    
    public void setMaxValue(Double maxValue) {
        this.maxValue = maxValue;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    public String getColour() {
        return this.colour;
    }
    
    public void setColour(String colour) {
        this.colour = colour;
    }

    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
   
    public Set getSbiAlarms() {
        return this.sbiAlarms;
    }
    
    public void setSbiAlarms(Set sbiAlarms) {
        this.sbiAlarms = sbiAlarms;
    }

}
