ALTER TABLE SBI_OBJECT_NOTES ADD  OWNER VARCHAR2 (50);
ALTER TABLE SBI_OBJECT_NOTES ADD  ISPUBLIC SMALLINT;
ALTER TABLE SBI_OBJECT_NOTES ADD  (CREATION_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL );
ALTER TABLE SBI_OBJECT_NOTES ADD  (LAST_CHANGE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL );
ALTER TABLE SBI_SUBOBJECTS MODIFY DESCRIPTION VARCHAR(1000) DEFAULT NULL;
ALTER TABLE SBI_DATA_SET` ADD (DS_METADATA VARCHAR(2000) DEFAULT NULL);

/* Modifies for add possibility to update subobjects. It's necessary delete all subobjects where 
name is null because we add not null constraint to name column. */
DELETE FROM SBI_REMEMBER_ME WHERE SUBOBJ_ID IN (SELECT SUBOBJ_ID FROM SBI_SUBOBJECTS WHERE NAME IS NULL OR NAME ='');
DELETE FROM SBI_AUDIT WHERE SUBOBJ_ID IN (SELECT SUBOBJ_ID FROM SBI_SUBOBJECTS WHERE NAME IS NULL OR NAME ='');
DELETE FROM SBI_MENU WHERE SUBOBJ_NAME IN (SELECT NAME FROM SBI_SUBOBJECTS WHERE NAME IS NULL OR NAME ='');
DELETE FROM SBI_BINARY_CONTENTS WHERE BIN_ID IN (SELECT BIN_ID FROM SBI_SUBOBJECTS WHERE NAME IS NULL OR NAME ='');
DELETE FROM SBI_SUBOBJECTS WHERE NAME IS NULL OR NAME ='';
COMMIT;
ALTER TABLE SBI_SUBOBJECTS MODIFY NAME VARCHAR2(50) NOT NULL;