ALTER TABLE SBI_OBJECT_NOTES ADD  OWNER VARCHAR2 (50);
ALTER TABLE SBI_OBJECT_NOTES ADD  ISPUBLIC SMALLINT;
ALTER TABLE SBI_OBJECT_NOTES ADD  (CREATION_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL );
ALTER TABLE SBI_OBJECT_NOTES ADD  (LAST_CHANGE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL );
ALTER TABLE SBI_SUBOBJECTS MODIFY DESCRIPTION VARCHAR(1000) DEFAULT NULL;
ALTER TABLE SBI_DATA_SET` ADD (DS_METADATA VARCHAR(2000) DEFAULT NULL);