DROP TABLE SBI_EVENTS_ROLES CASCADE ;
DROP TABLE SBI_EVENTS_LOG CASCADE ;
DROP TABLE SBI_EVENTS CASCADE ;
DROP TABLE SBI_SUBREPORTS CASCADE ;
DROP TABLE SBI_OBJ_PARUSE CASCADE ;
DROP TABLE SBI_PARUSE_CK CASCADE ;
DROP TABLE SBI_PARUSE_DET CASCADE ;
DROP TABLE SBI_PARUSE CASCADE ;
DROP TABLE SBI_FUNC_ROLE CASCADE ;
DROP TABLE SBI_OBJ_FUNC CASCADE ;
DROP TABLE SBI_FUNCTIONS CASCADE ;
DROP TABLE SBI_CHECKS CASCADE ;
DROP TABLE SBI_OBJ_PAR CASCADE ;
DROP TABLE SBI_PARAMETERS CASCADE ;
DROP TABLE SBI_OBJ_STATE CASCADE ;
DROP TABLE SBI_OBJECTS CASCADE ;
DROP TABLE SBI_EXT_ROLES CASCADE ;
DROP TABLE SBI_LOV CASCADE ;
DROP TABLE SBI_ENGINES CASCADE ;
DROP TABLE SBI_DOMAINS CASCADE ;


