/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiDomains generated by hbm2java
 */
public class SbiDomains  implements java.io.Serializable {

    // Fields    

     private Integer valueId;
     private String domainCd;
     private String domainNm;
     private String valueCd;
     private String valueNm;
     private String valueDs;
	

    // Constructors

    /** default constructor */
    public SbiDomains() {
    }
    
    /** constructor with id */
    public SbiDomains(Integer valueId) {
        this.valueId = valueId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getValueId() {
        return this.valueId;
    }
    
    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }

    /**
     * 
     */
    public String getDomainCd() {
        return this.domainCd;
    }
    
    public void setDomainCd(String domainCd) {
        this.domainCd = domainCd;
    }

    /**
     * 
     */
    public String getDomainNm() {
        return this.domainNm;
    }
    
    public void setDomainNm(String domainNm) {
        this.domainNm = domainNm;
    }

    /**
     * 
     */
    public String getValueCd() {
        return this.valueCd;
    }
    
    public void setValueCd(String valueCd) {
        this.valueCd = valueCd;
    }

    /**
     * 
     */
    public String getValueNm() {
        return this.valueNm;
    }
    
    public void setValueNm(String valueNm) {
        this.valueNm = valueNm;
    }

    /**
     * 
     */
    public String getValueDs() {
        return this.valueDs;
    }
    
    public void setValueDs(String valueDs) {
        this.valueDs = valueDs;
    }



}