document.write('<script type="text/javascript">if(!window.qxsettings)qxsettings={};\
if(qxsettings["qx.resourceUri"]==undefined)qxsettings["qx.resourceUri"]="../../../../frontend/framework/source/resource";\
if(qxsettings["apiviewer.resourceUri"]==undefined)qxsettings["apiviewer.resourceUri"]="./resource";\
if(qxsettings["qx.theme"]==undefined)qxsettings["qx.theme"]="qx.theme.ClassicRoyale";\
if(qxsettings["qx.minLogLevel"]==undefined)qxsettings["qx.minLogLevel"]=200;\
if(qxsettings["qx.logAppender"]==undefined)qxsettings["qx.logAppender"]="qx.log.appender.Native";\
if(qxsettings["qx.application"]==undefined)qxsettings["qx.application"]="apiviewer.Application";\
if(qxsettings["qx.version"]==undefined)qxsettings["qx.version"]="0.7.3 ";\
if(qxsettings["qx.isSource"]==undefined)qxsettings["qx.isSource"]=true;\
if(!window.qxvariants)qxvariants={};\
</script><script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Bootstrap.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/lang/Core.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/lang/Generics.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Setting.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/lang/Array.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Variant.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Aspect.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Client.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/lang/Object.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/Class.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/Mixin.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/Interface.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/locale/MTranslation.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/MLogging.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/MUserData.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/LegacyProperty.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Property.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/lang/String.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Object.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Log.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/lang/Function.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/bom/Viewport.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/Theme.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Target.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/type/Event.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/type/DataEvent.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/type/ChangeEvent.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/Filter.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/DefaultFilter.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/LogEventProcessor.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/appender/Abstract.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/appender/Window.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/client/Timer.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/appender/FireBug.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/appender/Native.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/log/Logger.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/dev/StackTrace.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/String.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/dom/String.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/Entity.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/EventRegistration.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Init.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/application/IApplication.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/core/Version.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/OO.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/classic/color/Royale.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/classic/Border.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/classic/font/Default.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/util/manager/Value.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/Alias.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/classic/Widget.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/classic/Appearance.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/icon/Nuvola.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/ClassicRoyale.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/application/Gui.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/core/Widget.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/Dimension.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/Style.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/StyleSheet.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/core/Parent.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/type/FocusEvent.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/handler/EventHandler.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/dom/Node.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/handler/KeyEventHandler.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/type/DomEvent.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/type/KeyEvent.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/type/MouseEvent.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/util/manager/Object.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/embed/IframeManager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/CanvasLayout.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/impl/LayoutImpl.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/lang/Number.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/impl/CanvasLayoutImpl.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/core/ClientDocument.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/basic/Terminator.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/core/ClientDocumentBlocker.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/manager/Appearance.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/manager/Meta.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/manager/Color.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/util/ColorUtil.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/manager/Border.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/core/Border.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/manager/Font.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/core/Font.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/manager/Icon.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/theme/manager/Widget.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/event/handler/FocusHandler.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/Location.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/Scroll.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/image/Manager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/Offset.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/ScrollIntoView.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/image/PreloaderSystem.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/image/PreloaderManager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/image/Preloader.js"></script>\
<script type="text/javascript" src="./class/apiviewer/Application.js"></script>\
<script type="text/javascript" src="./class/apiviewer/MWidgetRegistry.js"></script>\
<script type="text/javascript" src="./class/apiviewer/TreeUtil.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/DockLayout.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/impl/DockLayoutImpl.js"></script>\
<script type="text/javascript" src="./class/apiviewer/Viewer.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/BoxLayout.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/impl/VerticalBoxLayoutImpl.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/util/Validation.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/impl/HorizontalBoxLayoutImpl.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/tree/AbstractTreeElement.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/tree/TreeRowStructure.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/embed/HtmlEmbed.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/basic/Image.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/basic/Label.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/locale/Manager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/locale/LocalizedString.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/dom/Element.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/tree/TreeFolder.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/tree/Tree.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/selection/SelectionManager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/selection/Selection.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/tree/SelectionManager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/tree/TreeFile.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/HorizontalBoxLayout.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/VerticalBoxLayout.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/PackageTree.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/SearchView.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/form/TextField.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/basic/Atom.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/form/Button.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/toolbar/Button.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/popup/Popup.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/popup/PopupManager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/util/Compare.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/util/Normalization.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/bom/element/Location.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/bom/element/Style.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/bom/element/Dimension.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/bom/Document.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/popup/PopupAtom.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/popup/ToolTip.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/popup/ToolTipManager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/form/CheckBox.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/form/InputCheckSymbol.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/ListView.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/Header.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/HeaderCell.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/basic/HorizontalSpacer.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/HeaderSeparator.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/GridLayout.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/layout/impl/GridLayoutImpl.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/ListViewPane.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/SelectionManager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/ContentCellHtml.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/embed/IconHtmlEmbed.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/ContentCellIconHtml.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/ContentCellImage.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/embed/LinkEmbed.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/ContentCellLink.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/embed/TextEmbed.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/listview/ContentCellText.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/basic/ScrollBar.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/basic/ScrollArea.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/net/Http.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/util/Mime.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/remote/Request.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/remote/RequestQueue.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/remote/Exchange.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/remote/Response.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/remote/AbstractRemoteTransport.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/remote/XmlHttpTransport.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/net/HttpRequest.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/Json.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/remote/IframeTransport.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/html/Iframe.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/io/remote/ScriptTransport.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Node.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Class.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/ClassItem.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Method.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Param.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Event.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Property.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/AbstractViewer.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ObjectRegistry.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/dev/Tokenizer.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/util/StringBuilder.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/ClassViewer.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/panels/InfoPanel.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Package.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/panels/MethodPanel.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/panels/EventPanel.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/panels/PropertyPanel.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/panels/ConstantPanel.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/panels/AppearancePanel.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Constant.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/Appearance.js"></script>\
<script type="text/javascript" src="./class/apiviewer/dao/State.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/LegendView.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/AbstractPageView.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/buttonview/ButtonView.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/AbstractBar.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/selection/RadioManager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/buttonview/Bar.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/AbstractPane.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/buttonview/Pane.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/AbstractButton.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/buttonview/Button.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/AbstractPage.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/pageview/buttonview/Page.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/toolbar/ToolBar.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/toolbar/MenuButton.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/toolbar/Part.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/toolbar/PartHandle.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/menu/Manager.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/toolbar/CheckBox.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/PackageViewer.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/panels/ClassPanel.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ui/panels/PackagePanel.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/splitpane/SplitPane.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/splitpane/SplitPaneSlider.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/splitpane/SplitPaneSplitter.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/splitpane/SplitPaneKnob.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/ui/splitpane/HorizontalSplitPane.js"></script>\
<script type="text/javascript" src="./class/apiviewer/Controller.js"></script>\
<script type="text/javascript" src="./class/apiviewer/ClassLoader.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/client/History.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/locale/Locale.js"></script>\
<script type="text/javascript" src="../../../../frontend/framework/source/class/qx/locale/data/C.js"></script>\
');