package it.eng.spagobi.analiticalmodel.document.metadata;
// Generated 23-apr-2008 15.08.55 by Hibernate Tools 3.1.0 beta3



/**
 * SbiObjectsRatingId generated by hbm2java
 */

public class SbiObjectsRatingId  implements java.io.Serializable {


    // Fields    

     private Integer objId;
     private String userId;


    // Constructors

    /** default constructor */
    public SbiObjectsRatingId() {
    }

    
    /** full constructor */
    public SbiObjectsRatingId(Integer objId, String userId) {
        this.objId = objId;
        this.userId = userId;
    }
    

   
    // Property accessors

    public Integer getObjId() {
        return this.objId;
    }
    
    public void setObjId(Integer objId) {
        this.objId = objId;
    }

    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiObjectsRatingId) ) return false;
		 SbiObjectsRatingId castOther = ( SbiObjectsRatingId ) other; 
         
		 return ( (this.getObjId()==castOther.getObjId()) || ( this.getObjId()!=null && castOther.getObjId()!=null && this.getObjId().equals(castOther.getObjId()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getObjId() == null ? 0 : this.getObjId().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         return result;
   }   





}
