package it.eng.spagobi.geo.bo;


// Generated 31-mag-2007 14.53.27 by Hibernate Tools 3.2.0.beta8

/**
 * SbiGeoMapFeatures generated by hbm2java
 */
public class SbiGeoMapFeatures implements java.io.Serializable {

	// Fields    

	private SbiGeoMapFeaturesId id;

	private SbiGeoFeatures sbiGeoFeatures;

	private SbiGeoMaps sbiGeoMaps;

	private String svgGroup;

	private String visibleFlag;

	// Constructors

	/** default constructor */
	public SbiGeoMapFeatures() {
	}

	/** minimal constructor */
	public SbiGeoMapFeatures(SbiGeoMapFeaturesId id,
			SbiGeoFeatures sbiGeoFeatures, SbiGeoMaps sbiGeoMaps) {
		this.id = id;
		this.sbiGeoFeatures = sbiGeoFeatures;
		this.sbiGeoMaps = sbiGeoMaps;
	}

	/** full constructor */
	public SbiGeoMapFeatures(SbiGeoMapFeaturesId id,
			SbiGeoFeatures sbiGeoFeatures, SbiGeoMaps sbiGeoMaps,
			String svgGroup, String visibleFlag) {
		this.id = id;
		this.sbiGeoFeatures = sbiGeoFeatures;
		this.sbiGeoMaps = sbiGeoMaps;
		this.svgGroup = svgGroup;
		this.visibleFlag = visibleFlag;
	}

	// Property accessors
	public SbiGeoMapFeaturesId getId() {
		return this.id;
	}

	public void setId(SbiGeoMapFeaturesId id) {
		this.id = id;
	}

	public SbiGeoFeatures getSbiGeoFeatures() {
		return this.sbiGeoFeatures;
	}

	public void setSbiGeoFeatures(SbiGeoFeatures sbiGeoFeatures) {
		this.sbiGeoFeatures = sbiGeoFeatures;
	}

	public SbiGeoMaps getSbiGeoMaps() {
		return this.sbiGeoMaps;
	}

	public void setSbiGeoMaps(SbiGeoMaps sbiGeoMaps) {
		this.sbiGeoMaps = sbiGeoMaps;
	}

	public String getSvgGroup() {
		return this.svgGroup;
	}

	public void setSvgGroup(String svgGroup) {
		this.svgGroup = svgGroup;
	}

	public String getVisibleFlag() {
		return this.visibleFlag;
	}

	public void setVisibleFlag(String visibleFlag) {
		this.visibleFlag = visibleFlag;
	}

}
