/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiObjParId generated by hbm2java
 */
public class SbiObjParId  implements java.io.Serializable {

    // Fields    

     private SbiParameters sbiParameters;
     private SbiObjects sbiObjects;
     private Integer prog;


    // Constructors

    /** default constructor */
    public SbiObjParId() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public SbiParameters getSbiParameters() {
        return this.sbiParameters;
    }
    
    public void setSbiParameters(SbiParameters sbiParameters) {
        this.sbiParameters = sbiParameters;
    }

    /**
     * 
     */
    public SbiObjects getSbiObjects() {
        return this.sbiObjects;
    }
    
    public void setSbiObjects(SbiObjects sbiObjects) {
        this.sbiObjects = sbiObjects;
    }

    /**
     * 
     */
    public Integer getProg() {
        return this.prog;
    }
    
    public void setProg(Integer prog) {
        this.prog = prog;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiObjParId) ) return false;
		 SbiObjParId castOther = ( SbiObjParId ) other; 
         
		 return (this.getSbiParameters()==castOther.getSbiParameters()) || ( this.getSbiParameters()!=null && castOther.getSbiParameters()!=null && this.getSbiParameters().equals(castOther.getSbiParameters()) )
 && (this.getSbiObjects()==castOther.getSbiObjects()) || ( this.getSbiObjects()!=null && castOther.getSbiObjects()!=null && this.getSbiObjects().equals(castOther.getSbiObjects()) )
 && (this.getProg()==castOther.getProg()) || ( this.getProg()!=null && castOther.getProg()!=null && this.getProg().equals(castOther.getProg()) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSbiParameters().hashCode();
         result = 37 * result + this.getSbiObjects().hashCode();
         result = 37 * result + this.getProg().hashCode();
         return result;
   }   


}