/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.metadata;

import java.util.*;




/**
 * SbiExtRoles generated by hbm2java
 */
public class SbiExtRoles  implements java.io.Serializable {

    // Fields    

     private Integer extRoleId;
     private SbiDomains roleType;
     private String roleTypeCode;
     private String code;
     private String name;
     private String descr;
     private Set sbiFuncRoles;
     private Set sbiParuseDets;


    // Constructors

    /** default constructor */
    public SbiExtRoles() {
    }
    
    /** constructor with id */
    public SbiExtRoles(Integer extRoleId) {
        this.extRoleId = extRoleId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getExtRoleId() {
        return this.extRoleId;
    }
    
    public void setExtRoleId(Integer extRoleId) {
        this.extRoleId = extRoleId;
    }

    /**
     * 
     */
    public SbiDomains getRoleType() {
        return this.roleType;
    }
    
    public void setRoleType(SbiDomains sbiDomains) {
        this.roleType = sbiDomains;
    }

    /**
     * 
     */
    public String getRoleTypeCode() {
        return this.roleTypeCode;
    }
    
    public void setRoleTypeCode(String roleTypeCd) {
        this.roleTypeCode = roleTypeCd;
    }

    /**
     * 
     */
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * 
     */
    public Set getSbiFuncRoles() {
        return this.sbiFuncRoles;
    }
    
    public void setSbiFuncRoles(Set sbiFuncRoles) {
        this.sbiFuncRoles = sbiFuncRoles;
    }

    /**
     * 
     */
    public Set getSbiParuseDets() {
        return this.sbiParuseDets;
    }
    
    public void setSbiParuseDets(Set sbiParuseDets) {
        this.sbiParuseDets = sbiParuseDets;
    }



}