INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(36,'QUERY','Query statement','INPUT_TYPE','Input mode and values','Query statement to load list of values to choose in');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(37,'JAVA_CLASS','Java class','INPUT_TYPE','Input mode and values','Java class to load list of values to choose in');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(38,'SCRIPT','Script to load values','INPUT_TYPE','Input mode and values','Script to load values');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(39,'FIX_LOV','Fixed list of values','INPUT_TYPE','Input mode and values','Predefined and hard coded list of values to choose in');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(40,'REPORT','Report','BIOBJ_TYPE','BI Object types','Basic business intelligence objects type');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(41,'OLAP','On-line analytical processing','BIOBJ_TYPE','BI Object types','Dimensional analysis of significant facts');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(42,'DATA_MINING','Data mining model','BIOBJ_TYPE','BI Object types','Model to find out hidden information in data');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(43,'DASH','Dashboard','BIOBJ_TYPE','BI Object types','Dashboard to monitor perfomance indicators');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(44,'BOOL','Boolean','VALUE_TYPE','Input value types to check','Boolean input value type');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(45,'SINGLE','Single value','VALUE_TYPE','Input value types to check','Only single value allowed');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(46,'MULTI','Multivalue','VALUE_TYPE','Input value types to check','Many values are allowed');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(47,'DATE','Date','PAR_TYPE','Parameter type','Parameter expects date values');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(48,'NUM','Number','PAR_TYPE','Parameter type','Parameter expects numerical values');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(49,'STRING','String','PAR_TYPE','Parameter type','Parameter expects textual values');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(50,'FUNCT','Functional role','ROLE_TYPE','User role type','Functional role for end users');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(51,'ADMIN','Administrative role','ROLE_TYPE','User role type','Administrative role for developer users');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(52,'SUSP','Suspended','STATE','Object state','Document temporanlly not in use');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(53,'PORTAL','External portal roles','ROLE_TYPE','User role type','Predefined roles in BI portal');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(54,'LOW_FUNCT','Low level functionality','FUNCT_TYPE','Functionality','BI Functionality joined to categories tree');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(55,'DEV','Development','STATE','Object state','Document in development phase');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(56,'TEST','Test','STATE','Object state','Document in testing phase');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(57,'REL','Released','STATE','Object state','Document released for end users use');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(58,'DATE','Date','CHECK','Check','Date');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(59,'REGEXP','Regexp','CHECK','Check','Regular Expression ');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(60,'MAXLENGTH','Max Length','CHECK','Check','Max Length');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(61,'RANGE','Range','CHECK','Check','Range');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(62,'DECIMALS','Decimal','CHECK','Check','Decimal');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(63,'MINLENGTH','Min Length','CHECK','Check','Min Length');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(64,'INTERNET ADDRESS','Internet Address','PRED_CHECK','Pred Check','Internet Address');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(65,'NUMERIC','Numeric','PRED_CHECK','Pred Check','Numeric');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(66,'ALFANUMERIC','Alfanumeric','PRED_CHECK','Pred Check','Alfanumeric');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(67,'LETTERSTRING','Letter String','PRED_CHECK','Pred Check','Letter');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(68,'MANDATORY','Mandatory','PRED_CHECK','Check','Mandatory');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(69,'FISCALCODE','Fiscal Code','PRED_CHECK','Pred Check','Fiscal Code');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(70,'EMAIL','E-Mail','PRED_CHECK','Pred Check','E-Mail');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(103,'DATAMART','Datamart Model','BIOBJ_TYPE','BI Object types','Basic business intelligence objects type');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(104,'EXT','External Engine','ENGINE_TYPE','Engine types','Business intelligence external engine of SpagoBI platform');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(105,'INT','Internal Engine','ENGINE_TYPE','Engine types','Business intelligence internal engine of SpagoBI platform');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(106,'MAP','Map','BIOBJ_TYPE','BI Object types','Map');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(107,'BOOKLET','Booklet','BIOBJ_TYPE','BI Object types','Booklet');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(108, 'LIST','List values selection','SELECTION_TYPE','Selection modality of parameter values','Single-value selection from a list');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(109, 'CHECK_LIST','CheckList values selection','SELECTION_TYPE','Selection modality of parameter values','Multi-value selection from a checklist');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(110, 'COMBOBOX','ComboBox values selection','SELECTION_TYPE','Selection modality of parameter values','Single value selection from a combobox');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(111, 'OFFICE_DOC','Office document','BIOBJ_TYPE','BI Object types','Office document');
INSERT INTO SBI_DOMAINS (VALUE_ID,VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES(112, 'ETL','ETL process','BIOBJ_TYPE','BI Object types','ETL process');

INSERT INTO SBI_ENGINES (ENCRYPT, NAME, DESCR, MAIN_URL, SECN_URL, OBJ_UPL_DIR, OBJ_USE_DIR, DRIVER_NM, LABEL, ENGINE_TYPE, CLASS_NM, BIOBJ_TYPE) VALUES(0,'Dashboard Internal Engine','Dashboard Internal Engine','','','','','','DashboardInternalEng',105,'it.eng.spagobi.engines.dashboard.SpagoBIDashboardInternalEngine',43);
INSERT INTO SBI_ENGINES (ENCRYPT, NAME, DESCR, MAIN_URL, SECN_URL, OBJ_UPL_DIR, OBJ_USE_DIR, DRIVER_NM, LABEL, ENGINE_TYPE, CLASS_NM, BIOBJ_TYPE) VALUES(0,'Booklet Internal Engine','Booklet Internal Engine','','','','','','BookletInternalEng',105,'it.eng.spagobi.booklets.engines.SpagoBIBookletInternalEngine',107);
INSERT INTO SBI_ENGINES (ENCRYPT, NAME, DESCR, MAIN_URL, SECN_URL, OBJ_UPL_DIR, OBJ_USE_DIR, DRIVER_NM, LABEL, ENGINE_TYPE, CLASS_NM, BIOBJ_TYPE) VALUES(0,'Office Document Internal Engine','Office Document Internal Engine','','','','','','OfficeDocumentInternalEng',105,'it.eng.spagobi.engines.officeDocuments.SpagoBIOfficeDocumentInternalEngine',111);
INSERT INTO SBI_ENGINES (ENCRYPT, NAME, DESCR, MAIN_URL, SECN_URL, OBJ_UPL_DIR, OBJ_USE_DIR, DRIVER_NM, LABEL, ENGINE_TYPE, CLASS_NM, BIOBJ_TYPE) VALUES(0,'Dashboard Composition Internal Engine','Dashboard Composition Internal Engine','','','','','','DashboardCompIE',105,'it.eng.spagobi.engines.dashboardscomposition.SpagoBIDashboardsCompositionInternalEngine',43);

INSERT INTO SBI_LOV (DESCR, LABEL, INPUT_TYPE_CD, DEFAULT_VAL, LOV_PROVIDER, INPUT_TYPE_ID, PROFILE_ATTR, NAME) VALUES('Current month of the year format mm','CURRENT_MONTH_YEAR','SCRIPT',NULL,'<SCRIPTLOV><SCRIPT>Date now = new Date();\u000d\u000aint month = now.getMonth() + 1;\u000d\u000aString monthStr = month.toString();\u000d\u000aif (month < 10) monthStr = ''0'' + monthStr;\u000d\u000areturnValue(monthStr);</SCRIPT><VALUE-COLUMN>VALUE</VALUE-COLUMN><DESCRIPTION-COLUMN>VALUE</DESCRIPTION-COLUMN><VISIBLE-COLUMNS>VALUE</VISIBLE-COLUMNS><INVISIBLE-COLUMNS></INVISIBLE-COLUMNS></SCRIPTLOV>',38,NULL,'Current month of the year');
INSERT INTO SBI_LOV (DESCR, LABEL, INPUT_TYPE_CD, DEFAULT_VAL, LOV_PROVIDER, INPUT_TYPE_ID, PROFILE_ATTR, NAME) VALUES('Current year format yyyy','CURRENT_YEAR','SCRIPT',NULL,'<SCRIPTLOV><SCRIPT>Date now = new Date();\u000d\u000aint year = now.getYear() + 1900;\u000d\u000aString yearStr = year.toString();\u000d\u000areturnValue(yearStr);</SCRIPT><VALUE-COLUMN>VALUE</VALUE-COLUMN><DESCRIPTION-COLUMN>VALUE</DESCRIPTION-COLUMN><VISIBLE-COLUMNS>VALUE</VISIBLE-COLUMNS><INVISIBLE-COLUMNS></INVISIBLE-COLUMNS></SCRIPTLOV>',38,NULL,'Current year');
INSERT INTO SBI_LOV (DESCR, LABEL, INPUT_TYPE_CD, DEFAULT_VAL, LOV_PROVIDER, INPUT_TYPE_ID, PROFILE_ATTR, NAME) VALUES('Current month format mm/yyyy','CURRENT_MONTH','SCRIPT',NULL,'<SCRIPTLOV><SCRIPT>Date now = new Date();\u000d\u000aint month = now.getMonth() + 1;\u000d\u000aString monthStr = month.toString();\u000d\u000aif (month < 10) monthStr = ''0'' + monthStr;\u000d\u000aint year = now.getYear() + 1900;\u000d\u000aString toReturn = monthStr + ''/'' + year.toString();\u000d\u000areturnValue(toReturn);</SCRIPT><VALUE-COLUMN>VALUE</VALUE-COLUMN><DESCRIPTION-COLUMN>VALUE</DESCRIPTION-COLUMN><VISIBLE-COLUMNS>VALUE</VISIBLE-COLUMNS><INVISIBLE-COLUMNS></INVISIBLE-COLUMNS></SCRIPTLOV>',38,NULL,'Current month');
INSERT INTO SBI_LOV (DESCR, LABEL, INPUT_TYPE_CD, DEFAULT_VAL, LOV_PROVIDER, INPUT_TYPE_ID, PROFILE_ATTR, NAME) VALUES('Current date format dd/mm/yyyy','CURRENT_DATE','SCRIPT',NULL,'<SCRIPTLOV><SCRIPT>Date now = new Date();\u000d\u000aint day = now.getDate();\u000d\u000aString dayStr = day.toString();\u000d\u000aif (day < 10) dayStr = ''0'' + dayStr;\u000d\u000aint month = now.getMonth() + 1;\u000d\u000aString monthStr = month.toString();\u000d\u000aif (month < 10) monthStr = ''0'' + monthStr;\u000d\u000aint year = now.getYear() + 1900;\u000d\u000aString toReturn = dayStr + ''/'' + monthStr + ''/'' + year.toString();\u000d\u000areturnValue(toReturn);</SCRIPT><VALUE-COLUMN>VALUE</VALUE-COLUMN><DESCRIPTION-COLUMN>VALUE</DESCRIPTION-COLUMN><VISIBLE-COLUMNS>VALUE</VISIBLE-COLUMNS><INVISIBLE-COLUMNS></INVISIBLE-COLUMNS></SCRIPTLOV>',38,NULL,'Current date');

INSERT INTO SBI_CHECKS (DESCR, LABEL, VALUE_TYPE_CD, VALUE_TYPE_ID, VALUE_1, VALUE_2, NAME) VALUES('Control if parameter is an Internet Address','CK-FIX-01','INTERNET ADDRESS',64,NULL,NULL,'Internet Address');
INSERT INTO SBI_CHECKS (DESCR, LABEL, VALUE_TYPE_CD, VALUE_TYPE_ID, VALUE_1, VALUE_2, NAME) VALUES('Control if  a parameter is Numeric','CK-FIX-02','NUMERIC',65,NULL,NULL,'Numeric');
INSERT INTO SBI_CHECKS (DESCR, LABEL, VALUE_TYPE_CD, VALUE_TYPE_ID, VALUE_1, VALUE_2, NAME) VALUES('Control if  a parameter is Alfanumeric','CK-FIX-03','ALFANUMERIC',66,NULL,NULL,'Alfanumeric');
INSERT INTO SBI_CHECKS (DESCR, LABEL, VALUE_TYPE_CD, VALUE_TYPE_ID, VALUE_1, VALUE_2, NAME) VALUES('Control if a parameter is a letter string','CK-FIX-04','LETTERSTRING',67,NULL,NULL,'Letter String');
INSERT INTO SBI_CHECKS (DESCR, LABEL, VALUE_TYPE_CD, VALUE_TYPE_ID, VALUE_1, VALUE_2, NAME) VALUES('Control if the parameter is present','CK-FIX-05','MANDATORY',68,NULL,NULL,'Mandatory');
INSERT INTO SBI_CHECKS (DESCR, LABEL, VALUE_TYPE_CD, VALUE_TYPE_ID, VALUE_1, VALUE_2, NAME) VALUES('Control if parameter is a Fiscal Code','CK-FIX-06','FISCALCODE',69,NULL,NULL,'Fiscal Code');
INSERT INTO SBI_CHECKS (DESCR, LABEL, VALUE_TYPE_CD, VALUE_TYPE_ID, VALUE_1, VALUE_2, NAME) VALUES('Control if parameter is a E-Mail','CK-FIX-07','EMAIL',70,NULL,NULL,'E-Mail');



