DROP TABLE SBI_AUDIT;
DROP TABLE SBI_EVENTS_ROLES;
DROP TABLE SBI_EVENTS_LOG;
DROP TABLE SBI_EVENTS;
DROP TABLE SBI_SUBREPORTS;
DROP TABLE SBI_OBJ_PARUSE;
DROP TABLE SBI_PARUSE_CK;
DROP TABLE SBI_PARUSE_DET;
DROP TABLE SBI_PARUSE;
DROP TABLE SBI_FUNC_ROLE;
DROP TABLE SBI_OBJ_FUNC;
DROP TABLE SBI_FUNCTIONS;
DROP TABLE SBI_CHECKS;
DROP TABLE SBI_OBJ_PAR;
DROP TABLE SBI_PARAMETERS;
DROP TABLE SBI_OBJ_STATE;
DROP TABLE SBI_OBJECTS;
DROP TABLE SBI_EXT_ROLES;
DROP TABLE SBI_LOV;
DROP TABLE SBI_ENGINES;
DROP TABLE SBI_DOMAINS;
DROP TABLE SBI_GEO_MAP_FEATURES;
DROP TABLE SBI_GEO_FEATURES;
DROP TABLE SBI_GEO_MAPS;
DROP TABLE SBI_VIEWPOINTS;


