package it.eng.spagobi.kpi.metadata;
// Generated 3-nov-2008 10.09.04 by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * SbiKpi generated by hbm2java
 */

public class SbiKpi  implements java.io.Serializable {


    // Fields    

     private Integer kpiId;
     private SbiKpi sbiKpi;
     private SbiThreshold sbiThreshold;
     private SbiMeasureUnit sbiMeasureUnit;
     private Integer dsId;
     private String name;
     private String documentLabel;
     private String code;
     private String metric;
     private String description;
     private double standardWeight;
     private Character flgIsFather;
     private Set sbiKpiRoles = new HashSet(0);
     private Set sbiKpiModels = new HashSet(0);
     private Set sbiKpiInstances = new HashSet(0);
     private Set sbiKpis = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiKpi() {
    }

	/** minimal constructor */
    public SbiKpi(Integer kpiId, SbiKpi sbiKpi, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit, Integer dsId) {
        this.kpiId = kpiId;
        this.sbiKpi = sbiKpi;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
        this.dsId = dsId;
    }
    
    /** full constructor */
    public SbiKpi(Integer kpiId, SbiKpi sbiKpi, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit, Integer dsId, String name, String documentLabel, String code, String metric, String description, double standardWeight, Character flgIsFather, Set sbiKpiRoles, Set sbiKpiModels, Set sbiKpiInstances, Set sbiKpis) {
        this.kpiId = kpiId;
        this.sbiKpi = sbiKpi;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
        this.dsId = dsId;
        this.name = name;
        this.documentLabel = documentLabel;
        this.code = code;
        this.metric = metric;
        this.description = description;
        this.standardWeight = standardWeight;
        this.flgIsFather = flgIsFather;
        this.sbiKpiRoles = sbiKpiRoles;
        this.sbiKpiModels = sbiKpiModels;
        this.sbiKpiInstances = sbiKpiInstances;
        this.sbiKpis = sbiKpis;
    }
    

   
    // Property accessors

    public Integer getKpiId() {
        return this.kpiId;
    }
    
    public void setKpiId(Integer kpiId) {
        this.kpiId = kpiId;
    }

    public SbiKpi getSbiKpi() {
        return this.sbiKpi;
    }
    
    public void setSbiKpi(SbiKpi sbiKpi) {
        this.sbiKpi = sbiKpi;
    }

    public SbiThreshold getSbiThreshold() {
        return this.sbiThreshold;
    }
    
    public void setSbiThreshold(SbiThreshold sbiThreshold) {
        this.sbiThreshold = sbiThreshold;
    }

    public SbiMeasureUnit getSbiMeasureUnit() {
        return this.sbiMeasureUnit;
    }
    
    public void setSbiMeasureUnit(SbiMeasureUnit sbiMeasureUnit) {
        this.sbiMeasureUnit = sbiMeasureUnit;
    }

    public Integer getDsId() {
        return this.dsId;
    }
    
    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDocumentLabel() {
        return this.documentLabel;
    }
    
    public void setDocumentLabel(String documentLabel) {
        this.documentLabel = documentLabel;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getMetric() {
        return this.metric;
    }
    
    public void setMetric(String metric) {
        this.metric = metric;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public double getStandardWeight() {
        return this.standardWeight;
    }
    
    public void setStandardWeight(double standardWeight) {
        this.standardWeight = standardWeight;
    }

    public Character getFlgIsFather() {
        return this.flgIsFather;
    }
    
    public void setFlgIsFather(Character flgIsFather) {
        this.flgIsFather = flgIsFather;
    }

    public Set getSbiKpiRoles() {
        return this.sbiKpiRoles;
    }
    
    public void setSbiKpiRoles(Set sbiKpiRoles) {
        this.sbiKpiRoles = sbiKpiRoles;
    }

    public Set getSbiKpiModels() {
        return this.sbiKpiModels;
    }
    
    public void setSbiKpiModels(Set sbiKpiModels) {
        this.sbiKpiModels = sbiKpiModels;
    }

    public Set getSbiKpiInstances() {
        return this.sbiKpiInstances;
    }
    
    public void setSbiKpiInstances(Set sbiKpiInstances) {
        this.sbiKpiInstances = sbiKpiInstances;
    }

    public Set getSbiKpis() {
        return this.sbiKpis;
    }
    
    public void setSbiKpis(Set sbiKpis) {
        this.sbiKpis = sbiKpis;
    }
   








}
