package it.eng.spagobi.kpi.metadata;
// Generated 3-nov-2008 10.09.04 by Hibernate Tools 3.1.0 beta3



/**
 * SbiKpiPeriodicity generated by hbm2java
 */

public class SbiKpiPeriodicity  implements java.io.Serializable {


    // Fields    

     private Integer idKpiInstancePeriod;
     private SbiPeriodicity sbiPeriodicity;
     private SbiKpiInstance sbiKpiInstance;
     private Integer idKpiInstance;
     private double perValue;


    // Constructors

    /** default constructor */
    public SbiKpiPeriodicity() {
    }

	/** minimal constructor */
    public SbiKpiPeriodicity(Integer idKpiInstancePeriod, SbiPeriodicity sbiPeriodicity, SbiKpiInstance sbiKpiInstance, Integer idKpiInstance) {
        this.idKpiInstancePeriod = idKpiInstancePeriod;
        this.sbiPeriodicity = sbiPeriodicity;
        this.sbiKpiInstance = sbiKpiInstance;
        this.idKpiInstance = idKpiInstance;
    }
    
    /** full constructor */
    public SbiKpiPeriodicity(Integer idKpiInstancePeriod, SbiPeriodicity sbiPeriodicity, SbiKpiInstance sbiKpiInstance, Integer idKpiInstance, double perValue) {
        this.idKpiInstancePeriod = idKpiInstancePeriod;
        this.sbiPeriodicity = sbiPeriodicity;
        this.sbiKpiInstance = sbiKpiInstance;
        this.idKpiInstance = idKpiInstance;
        this.perValue = perValue;
    }
    

   
    // Property accessors

    public Integer getIdKpiInstancePeriod() {
        return this.idKpiInstancePeriod;
    }
    
    public void setIdKpiInstancePeriod(Integer idKpiInstancePeriod) {
        this.idKpiInstancePeriod = idKpiInstancePeriod;
    }

    public SbiPeriodicity getSbiPeriodicity() {
        return this.sbiPeriodicity;
    }
    
    public void setSbiPeriodicity(SbiPeriodicity sbiPeriodicity) {
        this.sbiPeriodicity = sbiPeriodicity;
    }

    public SbiKpiInstance getSbiKpiInstance() {
        return this.sbiKpiInstance;
    }
    
    public void setSbiKpiInstance(SbiKpiInstance sbiKpiInstance) {
        this.sbiKpiInstance = sbiKpiInstance;
    }

    public Integer getIdKpiInstance() {
        return this.idKpiInstance;
    }
    
    public void setIdKpiInstance(Integer idKpiInstance) {
        this.idKpiInstance = idKpiInstance;
    }

    public double getPerValue() {
        return this.perValue;
    }
    
    public void setPerValue(double perValue) {
        this.perValue = perValue;
    }
   








}
