package it.eng.spagobi.kpi.metadata;
// Generated 3-nov-2008 10.09.05 by Hibernate Tools 3.1.0 beta3

import java.util.Date;


/**
 * SbiKpiValue generated by hbm2java
 */

public class SbiKpiValue  implements java.io.Serializable {


    // Fields    

     private Integer idKpiInstanceValue;
     private SbiKpiInstance sbiKpiInstance;
     private String kpiValue;
     private Date kpiDate;
     private String idDocumentMeasRes;
     private Date beginDt;
     private Date endDt;


    // Constructors

    /** default constructor */
    public SbiKpiValue() {
    }

	/** minimal constructor */
    public SbiKpiValue(Integer idKpiInstanceValue, SbiKpiInstance sbiKpiInstance) {
        this.idKpiInstanceValue = idKpiInstanceValue;
        this.sbiKpiInstance = sbiKpiInstance;
    }
    
    /** full constructor */
    public SbiKpiValue(Integer idKpiInstanceValue, SbiKpiInstance sbiKpiInstance, String kpiValue, Date kpiDate, String idDocumentMeasRes, Date beginDt, Date endDt) {
        this.idKpiInstanceValue = idKpiInstanceValue;
        this.sbiKpiInstance = sbiKpiInstance;
        this.kpiValue = kpiValue;
        this.kpiDate = kpiDate;
        this.idDocumentMeasRes = idDocumentMeasRes;
        this.beginDt = beginDt;
        this.endDt = endDt;
    }
    

   
    // Property accessors

    public Integer getIdKpiInstanceValue() {
        return this.idKpiInstanceValue;
    }
    
    public void setIdKpiInstanceValue(Integer idKpiInstanceValue) {
        this.idKpiInstanceValue = idKpiInstanceValue;
    }

    public SbiKpiInstance getSbiKpiInstance() {
        return this.sbiKpiInstance;
    }
    
    public void setSbiKpiInstance(SbiKpiInstance sbiKpiInstance) {
        this.sbiKpiInstance = sbiKpiInstance;
    }

    public String getKpiValue() {
        return this.kpiValue;
    }
    
    public void setKpiValue(String kpiValue) {
        this.kpiValue = kpiValue;
    }

    public Date getKpiDate() {
        return this.kpiDate;
    }
    
    public void setKpiDate(Date kpiDate) {
        this.kpiDate = kpiDate;
    }

    public String getIdDocumentMeasRes() {
        return this.idDocumentMeasRes;
    }
    
    public void setIdDocumentMeasRes(String idDocumentMeasRes) {
        this.idDocumentMeasRes = idDocumentMeasRes;
    }

    public Date getBeginDt() {
        return this.beginDt;
    }
    
    public void setBeginDt(Date beginDt) {
        this.beginDt = beginDt;
    }

    public Date getEndDt() {
        return this.endDt;
    }
    
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }
   








}
