package it.eng.spagobi.kpi.metadata;
// Generated 3-nov-2008 10.09.04 by Hibernate Tools 3.1.0 beta3



/**
 * SbiKpiModelAttrVal generated by hbm2java
 */

public class SbiKpiModelAttrVal  implements java.io.Serializable {


    // Fields    

     private Integer kpiModelAttrValId;
     private SbiKpiModelAttr sbiKpiModelAttr;
     private SbiKpiModel sbiKpiModel;
     private String attrValue;


    // Constructors

    /** default constructor */
    public SbiKpiModelAttrVal() {
    }

	/** minimal constructor */
    public SbiKpiModelAttrVal(Integer kpiModelAttrValId, SbiKpiModelAttr sbiKpiModelAttr, SbiKpiModel sbiKpiModel) {
        this.kpiModelAttrValId = kpiModelAttrValId;
        this.sbiKpiModelAttr = sbiKpiModelAttr;
        this.sbiKpiModel = sbiKpiModel;
    }
    
    /** full constructor */
    public SbiKpiModelAttrVal(Integer kpiModelAttrValId, SbiKpiModelAttr sbiKpiModelAttr, SbiKpiModel sbiKpiModel, String attrValue) {
        this.kpiModelAttrValId = kpiModelAttrValId;
        this.sbiKpiModelAttr = sbiKpiModelAttr;
        this.sbiKpiModel = sbiKpiModel;
        this.attrValue = attrValue;
    }
    

   
    // Property accessors

    public Integer getKpiModelAttrValId() {
        return this.kpiModelAttrValId;
    }
    
    public void setKpiModelAttrValId(Integer kpiModelAttrValId) {
        this.kpiModelAttrValId = kpiModelAttrValId;
    }

    public SbiKpiModelAttr getSbiKpiModelAttr() {
        return this.sbiKpiModelAttr;
    }
    
    public void setSbiKpiModelAttr(SbiKpiModelAttr sbiKpiModelAttr) {
        this.sbiKpiModelAttr = sbiKpiModelAttr;
    }

    public SbiKpiModel getSbiKpiModel() {
        return this.sbiKpiModel;
    }
    
    public void setSbiKpiModel(SbiKpiModel sbiKpiModel) {
        this.sbiKpiModel = sbiKpiModel;
    }

    public String getAttrValue() {
        return this.attrValue;
    }
    
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }
   








}
