package it.eng.spagobi.kpi.metadata;
// Generated 3-nov-2008 10.09.05 by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * SbiThreshold generated by hbm2java
 */

public class SbiThreshold  implements java.io.Serializable {


    // Fields    

     private Integer thresholdId;
     private Integer thresholdTypeId;
     private String name;
     private String description;
     private Set sbiKpis = new HashSet(0);
     private Set sbiThresholdValues = new HashSet(0);
     private Set sbiKpiInstances = new HashSet(0);
     private Set sbiKpiInstanceHistories = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiThreshold() {
    }

	/** minimal constructor */
    public SbiThreshold(Integer thresholdId, Integer thresholdTypeId) {
        this.thresholdId = thresholdId;
        this.thresholdTypeId = thresholdTypeId;
    }
    
    /** full constructor */
    public SbiThreshold(Integer thresholdId, Integer thresholdTypeId, String name, String description, Set sbiKpis, Set sbiThresholdValues, Set sbiKpiInstances, Set sbiKpiInstanceHistories) {
        this.thresholdId = thresholdId;
        this.thresholdTypeId = thresholdTypeId;
        this.name = name;
        this.description = description;
        this.sbiKpis = sbiKpis;
        this.sbiThresholdValues = sbiThresholdValues;
        this.sbiKpiInstances = sbiKpiInstances;
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
    }
    

   
    // Property accessors

    public Integer getThresholdId() {
        return this.thresholdId;
    }
    
    public void setThresholdId(Integer thresholdId) {
        this.thresholdId = thresholdId;
    }

    public Integer getThresholdTypeId() {
        return this.thresholdTypeId;
    }
    
    public void setThresholdTypeId(Integer thresholdTypeId) {
        this.thresholdTypeId = thresholdTypeId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getSbiKpis() {
        return this.sbiKpis;
    }
    
    public void setSbiKpis(Set sbiKpis) {
        this.sbiKpis = sbiKpis;
    }

    public Set getSbiThresholdValues() {
        return this.sbiThresholdValues;
    }
    
    public void setSbiThresholdValues(Set sbiThresholdValues) {
        this.sbiThresholdValues = sbiThresholdValues;
    }

    public Set getSbiKpiInstances() {
        return this.sbiKpiInstances;
    }
    
    public void setSbiKpiInstances(Set sbiKpiInstances) {
        this.sbiKpiInstances = sbiKpiInstances;
    }

    public Set getSbiKpiInstanceHistories() {
        return this.sbiKpiInstanceHistories;
    }
    
    public void setSbiKpiInstanceHistories(Set sbiKpiInstanceHistories) {
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
    }
   








}
