package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SbiAttribute generated by hbm2java
 */
public class SbiAttribute implements java.io.Serializable {

	private int attributeId;
	private String attributeName;
	private String description;
	private Set<SbiUserAttributes> sbiUserAttributeses = new HashSet<SbiUserAttributes>(
			0);

	public SbiAttribute() {
	}

	public SbiAttribute(int attributeId, String attributeName,
			String description) {
		this.attributeId = attributeId;
		this.attributeName = attributeName;
		this.description = description;
	}

	public SbiAttribute(int attributeId, String attributeName,
			String description, Set<SbiUserAttributes> sbiUserAttributeses) {
		this.attributeId = attributeId;
		this.attributeName = attributeName;
		this.description = description;
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<SbiUserAttributes> getSbiUserAttributeses() {
		return this.sbiUserAttributeses;
	}

	public void setSbiUserAttributeses(
			Set<SbiUserAttributes> sbiUserAttributeses) {
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

}
