package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 10.09.24 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SbiAttribute generated by hbm2java
 */
public class SbiAttribute implements java.io.Serializable {

	private int attributeId;
	private String attributeName;
	private String description;
	private Set<SbiUser> sbiUsers = new HashSet<SbiUser>(0);

	public SbiAttribute() {
	}

	public SbiAttribute(int attributeId, String attributeName,
			String description) {
		this.attributeId = attributeId;
		this.attributeName = attributeName;
		this.description = description;
	}

	public SbiAttribute(int attributeId, String attributeName,
			String description, Set<SbiUser> sbiUsers) {
		this.attributeId = attributeId;
		this.attributeName = attributeName;
		this.description = description;
		this.sbiUsers = sbiUsers;
	}

	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<SbiUser> getSbiUsers() {
		return this.sbiUsers;
	}

	public void setSbiUsers(Set<SbiUser> sbiUsers) {
		this.sbiUsers = sbiUsers;
	}

}
