package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 10.09.24 by Hibernate Tools 3.2.4.GA

/**
 * SbiExtUserRolesId generated by hbm2java
 */
public class SbiExtUserRolesId implements java.io.Serializable {

	private int id;
	private int extRoleId;

	public SbiExtUserRolesId() {
	}

	public SbiExtUserRolesId(int id, int extRoleId) {
		this.id = id;
		this.extRoleId = extRoleId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getExtRoleId() {
		return this.extRoleId;
	}

	public void setExtRoleId(int extRoleId) {
		this.extRoleId = extRoleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiExtUserRolesId))
			return false;
		SbiExtUserRolesId castOther = (SbiExtUserRolesId) other;

		return (this.getId() == castOther.getId())
				&& (this.getExtRoleId() == castOther.getExtRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getExtRoleId();
		return result;
	}

}
