package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 10.09.24 by Hibernate Tools 3.2.4.GA

/**
 * SbiExtUserRoles generated by hbm2java
 */
public class SbiExtUserRoles implements java.io.Serializable {

	private SbiExtUserRolesId id;
	private SbiUser sbiUser;

	public SbiExtUserRoles() {
	}

	public SbiExtUserRoles(SbiExtUserRolesId id, SbiUser sbiUser) {
		this.id = id;
		this.sbiUser = sbiUser;
	}

	public SbiExtUserRolesId getId() {
		return this.id;
	}

	public void setId(SbiExtUserRolesId id) {
		this.id = id;
	}

	public SbiUser getSbiUser() {
		return this.sbiUser;
	}

	public void setSbiUser(SbiUser sbiUser) {
		this.sbiUser = sbiUser;
	}

}
