package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SbiUser generated by hbm2java
 */
public class SbiUser implements java.io.Serializable {

	private int id;
	private String userId;
	private String password;
	private String fullName;
	
	private Set<SbiExtUserRoles> sbiExtUserRoleses = new HashSet<SbiExtUserRoles>(
			0);
	private Set<SbiUserAttributes> sbiUserAttributeses = new HashSet<SbiUserAttributes>(
			0);

	public SbiUser() {
	}

	public SbiUser(int id, String userId) {
		this.id = id;
		this.userId = userId;
	}

	public SbiUser(int id, String userId, String password, String fullName,
			Set<SbiExtUserRoles> sbiExtUserRoleses,
			Set<SbiUserAttributes> sbiUserAttributeses) {
		this.id = id;
		this.userId = userId;
		this.password = password;
		this.fullName = fullName;
		this.sbiExtUserRoleses = sbiExtUserRoleses;
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Set<SbiExtUserRoles> getSbiExtUserRoleses() {
		return this.sbiExtUserRoleses;
	}

	public void setSbiExtUserRoleses(Set<SbiExtUserRoles> sbiExtUserRoleses) {
		this.sbiExtUserRoleses = sbiExtUserRoleses;
	}

	public Set<SbiUserAttributes> getSbiUserAttributeses() {
		return this.sbiUserAttributeses;
	}

	public void setSbiUserAttributeses(
			Set<SbiUserAttributes> sbiUserAttributeses) {
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

}
