package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

/**
 * SbiUserAttributes generated by hbm2java
 */
public class SbiUserAttributes implements java.io.Serializable {

	private SbiUserAttributesId id;
	private SbiUser sbiUser;
	private SbiAttribute sbiAttribute;
	private String attributeValue;

	public SbiUserAttributes() {
	}

	public SbiUserAttributes(SbiUserAttributesId id, SbiUser sbiUser,
			SbiAttribute sbiAttribute) {
		this.id = id;
		this.sbiUser = sbiUser;
		this.sbiAttribute = sbiAttribute;
	}

	public SbiUserAttributes(SbiUserAttributesId id, SbiUser sbiUser,
			SbiAttribute sbiAttribute, String attributeValue) {
		this.id = id;
		this.sbiUser = sbiUser;
		this.sbiAttribute = sbiAttribute;
		this.attributeValue = attributeValue;
	}

	public SbiUserAttributesId getId() {
		return this.id;
	}

	public void setId(SbiUserAttributesId id) {
		this.id = id;
	}

	public SbiUser getSbiUser() {
		return this.sbiUser;
	}

	public void setSbiUser(SbiUser sbiUser) {
		this.sbiUser = sbiUser;
	}

	public SbiAttribute getSbiAttribute() {
		return this.sbiAttribute;
	}

	public void setSbiAttribute(SbiAttribute sbiAttribute) {
		this.sbiAttribute = sbiAttribute;
	}

	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

}
